/**
 * v2.0.0 seed — patient stories batch 7 (8 new patients).
 * EHRC-2026-036 through 043.
 */
import type { SeedPatient } from './types';

export const PATIENTS_BATCH_7: SeedPatient[] = [
  // 36. Lalitha Nayak — 48F — Banashankari — homemaker
  // Post-mastectomy, on tamoxifen, hot flashes
  {
    mrn: 'EHRC-2026-036', name: 'Lalitha Nayak', age_years: 48, sex: 'F',
    phone_e164: '+919844772233', known_allergies: null,
    occupation: 'Homemaker', area: 'Banashankari',
    primary_doctor_email: 'chandrika.kambam@even.in',
    active_problems: [
      { label: 'Breast cancer survivor (ER+, post-mastectomy 2024)', since: '2024-02', status: 'controlled',
        current_meds: ['Tamoxifen 20mg OD'] },
      { label: 'Treatment-induced menopausal symptoms', since: '2024-09', status: 'active' },
    ],
    encounters: [
      { date: '2025-07-30', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly oncology follow-up — surveillance. Hot flashes 4-6/day disturbing sleep.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 62, height_cm: 158, pain: 0 },
        exam_findings: 'Scar healed. No palpable axillary nodes. CVS normal.',
        assessment_codes: ['Z85.3'],
        assessment_text: 'Tamoxifen continuation. Hot flashes — non-hormonal management.',
        rx_lines: [
          { generic: 'Tamoxifen', brand: 'Nolvadex', strength: '20mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Venlafaxine', brand: 'Effexor', strength: '37.5mg', form: 'capsule', frequency: 'OD', duration_days: 90, instructions: 'For vasomotor symptoms.' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-11-12', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Surveillance + mammo result. Hot flashes 1-2/day.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 74, temp_c: 36.7, spo2: 98, weight_kg: 62, height_cm: 158, pain: 0 },
        exam_findings: 'No recurrence signs.',
        assessment_codes: ['Z85.3'],
        assessment_text: 'No recurrence. Mammography NAD.',
        rx_lines: [
          { generic: 'Tamoxifen', brand: 'Nolvadex', strength: '20mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Venlafaxine', brand: 'Effexor', strength: '37.5mg', form: 'capsule', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-26', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Spotting + pelvic discomfort over past 2 weeks. Worry: tamoxifen-related endometrial change.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 78, temp_c: 36.7, spo2: 98, weight_kg: 63, height_cm: 158, pain: 2 },
        exam_findings: 'No palpable mass per abdomen.',
        assessment_codes: ['N93.9'],
        assessment_text: 'TVS to assess endometrium given tamoxifen + spotting.',
        rx_lines: [{ generic: 'Tamoxifen', brand: 'Nolvadex', strength: '20mg', form: 'tablet', frequency: 'OD', duration_days: 90 }],
        disposition: 'diagnostics', referral_target: 'OBG — for TVS interpretation' },
      { date: '2026-05-12', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'TVS: endometrial thickness 7mm — borderline. OBG opinion: observe, repeat in 3 months.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 63, height_cm: 158, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['Z85.3'],
        assessment_text: 'Continue tamoxifen with active surveillance.',
        rx_lines: [
          { generic: 'Tamoxifen', brand: 'Nolvadex', strength: '20mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Venlafaxine', brand: 'Effexor', strength: '37.5mg', form: 'capsule', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-28', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [{ raw_text: 'CBC + LFT + Mammography', canonical_key: 'cancer_surveillance', display_name: 'Cancer Surveillance' }],
        results: [
          { canonical_key: 'mammography', display_name: 'Mammography', value_text: 'BIRADS 1. No suspicious mass. Stable post-surgical changes.', unit: '', reference_range: 'BIRADS 1-2' },
          { canonical_key: 'hemoglobin', display_name: 'Hemoglobin', value_numeric: 12.6, unit: 'g/dL', reference_range: '12.0-16.0' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 24, unit: 'U/L', reference_range: '7-56' },
        ] },
      { date: '2026-05-10', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [{ raw_text: 'TVS', canonical_key: 'tvs', display_name: 'Transvaginal Ultrasound' }],
        results: [{ canonical_key: 'tvs', display_name: 'TVS', value_text: 'Endometrial thickness 7mm. Heterogenous. No focal mass. Subendometrial halo intact.', unit: '', reference_range: '<5mm post-menopause' }] },
    ],
    override_events: [],
  },

  // 37. Anand Devaraj — 43M — Whitefield — IT manager
  // HIV+ on ART (long-term), recent CD4 stable
  {
    mrn: 'EHRC-2026-037', name: 'Anand Devaraj', age_years: 43, sex: 'M',
    phone_e164: '+919900778899', known_allergies: 'Sulfa drugs (severe rash, 2010)',
    occupation: 'IT manager', area: 'Whitefield',
    primary_doctor_email: 'aditya.sharma@even.in',
    active_problems: [
      { label: 'HIV-1 infection, on ART (since 2018)', since: '2018-03', status: 'controlled',
        current_meds: ['Tenofovir + Lamivudine + Dolutegravir (TLD)'] },
      { label: 'Dyslipidemia (ART-related)', since: '2022-09', status: 'controlled',
        current_meds: ['Rosuvastatin 10mg OD'] },
    ],
    encounters: [
      { date: '2025-07-08', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly review. Reports good health, no opportunistic infections.',
        vitals: { bp_sys: 122, bp_dia: 78, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 172, pain: 0 },
        exam_findings: 'No lymphadenopathy. Skin clear. No oral thrush.',
        assessment_codes: ['B20'],
        assessment_text: 'HIV controlled. VL undetectable, CD4 stable.',
        rx_lines: [
          { generic: 'Tenofovir + Lamivudine + Dolutegravir', brand: 'Tenoff-LD', strength: '300+300+50mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Rosuvastatin', brand: 'Rosuvas', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90, timing: 'HS' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-10-18', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly. Stable.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 172, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['B20'],
        assessment_text: 'Stable.',
        rx_lines: [
          { generic: 'Tenofovir + Lamivudine + Dolutegravir', brand: 'Tenoff-LD', strength: '300+300+50mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Rosuvastatin', brand: 'Rosuvas', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-01-28', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Cough', 'Fever'],
        cc_text: 'Recent URI symptoms, productive cough x 1 week. Concerned re: PCP given baseline.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 84, rr: 18, temp_c: 37.8, spo2: 96, weight_kg: 70, height_cm: 172, pain: 1 },
        exam_findings: 'Throat congested. Chest clear. No crepts.',
        assessment_codes: ['B20', 'J06.9'],
        assessment_text: 'Likely viral URI. Empirically cover if not better in 48h.',
        rx_lines: [
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'TDS PRN', duration_days: 5 },
          { generic: 'Levocetirizine', brand: 'Levocet', strength: '5mg', form: 'tablet', frequency: 'HS', duration_days: 5 },
        ],
        disposition: 'follow_up', follow_up_days: 5 },
      { date: '2026-04-22', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly. Doing well.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 70, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 172, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['B20'],
        assessment_text: 'VL undetectable, CD4 642.',
        rx_lines: [
          { generic: 'Tenofovir + Lamivudine + Dolutegravir', brand: 'Tenoff-LD', strength: '300+300+50mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Rosuvastatin', brand: 'Rosuvas', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-05', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'HIV VL + CD4 + Lipid + LFT', canonical_key: 'hiv_quarterly', display_name: 'HIV Quarterly Panel' }],
        results: [
          { canonical_key: 'hiv_viral_load', display_name: 'HIV-1 RNA VL', value_text: '<20 copies/mL (undetectable)', unit: '', reference_range: 'undetectable on ART' },
          { canonical_key: 'cd4', display_name: 'CD4 count', value_numeric: 612, unit: 'cells/µL', reference_range: '>500' },
          { canonical_key: 'ldl_cholesterol', display_name: 'LDL', value_numeric: 96, unit: 'mg/dL', reference_range: '<100' },
        ] },
      { date: '2026-04-20', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'HIV VL + CD4', canonical_key: 'hiv_quarterly', display_name: 'HIV Quarterly' }],
        results: [
          { canonical_key: 'hiv_viral_load', display_name: 'HIV-1 RNA VL', value_text: '<20 copies/mL', unit: '', reference_range: 'undetectable' },
          { canonical_key: 'cd4', display_name: 'CD4 count', value_numeric: 642, unit: 'cells/µL', reference_range: '>500' },
        ] },
    ],
    override_events: [],
  },

  // 38. Reema Lakra — 39F — Whitefield — HR specialist
  // Newly diagnosed RA, on methotrexate, recent flare
  {
    mrn: 'EHRC-2026-038', name: 'Reema Lakra', age_years: 39, sex: 'F',
    phone_e164: '+919845112299', known_allergies: null,
    occupation: 'HR specialist', area: 'Whitefield',
    primary_doctor_email: 'karthik.reddy@even.in',
    active_problems: [
      { label: 'Rheumatoid arthritis, seropositive', since: '2025-08', status: 'active',
        current_meds: ['Methotrexate 15mg weekly', 'Folic acid 5mg weekly', 'Hydroxychloroquine 200mg BD'] },
    ],
    encounters: [
      { date: '2025-08-15', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Joint pain'],
        cc_text: 'Polyarticular joint pain + morning stiffness >1hr, 3 months. Symmetric — wrists, MCPs, PIPs.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 78, temp_c: 36.9, spo2: 99, weight_kg: 58, height_cm: 160, pain: 6 },
        exam_findings: 'Bilateral synovitis MCPs + PIPs. Wrist tender. No deformity yet.',
        assessment_codes: ['M06.9'],
        assessment_text: 'Suspected RA. Refer to rheumatology while ordering ANA, RF, anti-CCP.',
        rx_lines: [
          { generic: 'Naproxen', brand: 'Naprosyn', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 14 },
          { generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 14 },
        ],
        disposition: 'refer', referral_target: 'Dr. Karthik · Ortho (rheumatology gateway)',
        handoff_note: 'Strong clinical RA picture — RF + anti-CCP pending. Please start DMARD if confirmed.' },
      { date: '2025-09-08', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain', 'Lab review'],
        cc_text: 'RF + Anti-CCP positive. Active synovitis ongoing.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 58, height_cm: 160, pain: 5 },
        exam_findings: 'Same.',
        assessment_codes: ['M06.0'],
        assessment_text: 'Seropositive RA confirmed. Start Methotrexate + HCQ.',
        rx_lines: [
          { generic: 'Methotrexate', brand: 'Folitrax', strength: '7.5mg', form: 'tablet', frequency: 'weekly', duration: '4 weeks', instructions: 'Up-titrate to 15mg over 4 weeks.' },
          { generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'weekly', duration: '3 months', instructions: 'Day after methotrexate.' },
          { generic: 'Hydroxychloroquine', brand: 'HCQS', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Prednisolone', brand: 'Wysolone', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 30, instructions: 'Bridge therapy. Taper.' },
        ],
        disposition: 'follow_up', follow_up_days: 30 },
      { date: '2025-12-10', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Improving. Morning stiffness 30 min from >1hr. Some PIPs still tender.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 58, height_cm: 160, pain: 3 },
        exam_findings: 'Less synovitis. DAS28 ~3.5.',
        assessment_codes: ['M06.0'],
        assessment_text: 'Responding. Continue. Steroid tapered off.',
        rx_lines: [
          { generic: 'Methotrexate', brand: 'Folitrax', strength: '15mg', form: 'tablet', frequency: 'weekly', duration: '3 months' },
          { generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'weekly', duration: '3 months' },
          { generic: 'Hydroxychloroquine', brand: 'HCQS', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-04-08', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Flare 2 weeks ago. Triggered by stress. Increased PIP swelling + new wrist pain.',
        vitals: { bp_sys: 120, bp_dia: 76, hr: 76, temp_c: 36.9, spo2: 99, weight_kg: 58, height_cm: 160, pain: 5 },
        exam_findings: 'Synovitis worse than December.',
        assessment_codes: ['M06.0'],
        assessment_text: 'Flare. Short steroid burst + consider biologic if persistent.',
        rx_lines: [
          { generic: 'Prednisolone', brand: 'Wysolone', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 21, instructions: 'Bridge taper.' },
          { generic: 'Methotrexate', brand: 'Folitrax', strength: '15mg', form: 'tablet', frequency: 'weekly', duration: '3 months' },
          { generic: 'Hydroxychloroquine', brand: 'HCQS', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 30,
        handoff_note: 'If still flaring at next visit, consider adding TNF inhibitor — patient is biologic-naive.' },
    ],
    lab_cycles: [
      { date: '2025-09-02', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'RA panel + ESR + CRP', canonical_key: 'ra_workup', display_name: 'RA Workup' }],
        results: [
          { canonical_key: 'rf', display_name: 'Rheumatoid Factor', value_numeric: 184, unit: 'IU/mL', reference_range: '<14' },
          { canonical_key: 'anti_ccp', display_name: 'Anti-CCP', value_numeric: 142, unit: 'U/mL', reference_range: '<20' },
          { canonical_key: 'esr', display_name: 'ESR', value_numeric: 48, unit: 'mm/hr', reference_range: '0-20' },
          { canonical_key: 'crp', display_name: 'CRP', value_numeric: 26, unit: 'mg/L', reference_range: '<5' },
        ] },
      { date: '2025-12-05', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [{ raw_text: 'ESR + CRP + LFT + Crea (MTX monitoring)', canonical_key: 'mtx_monitoring', display_name: 'MTX Monitoring' }],
        results: [
          { canonical_key: 'esr', display_name: 'ESR', value_numeric: 18, unit: 'mm/hr', reference_range: '0-20' },
          { canonical_key: 'crp', display_name: 'CRP', value_numeric: 4, unit: 'mg/L', reference_range: '<5' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 32, unit: 'U/L', reference_range: '7-56' },
        ] },
      { date: '2026-04-05', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [{ raw_text: 'ESR + CRP + LFT + Crea', canonical_key: 'mtx_monitoring', display_name: 'MTX Monitoring' }],
        results: [
          { canonical_key: 'esr', display_name: 'ESR', value_numeric: 34, unit: 'mm/hr', reference_range: '0-20' },
          { canonical_key: 'crp', display_name: 'CRP', value_numeric: 14, unit: 'mg/L', reference_range: '<5' },
        ] },
    ],
    override_events: [
      { date: '2025-09-08', doctor_email: 'karthik.reddy@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Rheumatoid arthritis, seropositive', status: 'active', note: 'RF + anti-CCP positive. DAS28 6.2 at start.' } },
    ],
  },

  // 39. Pradeep Acharya — 56M — Yelahanka — small business owner
  // Chronic Hep B, compensated cirrhosis (Child-Pugh A)
  {
    mrn: 'EHRC-2026-039', name: 'Pradeep Acharya', age_years: 56, sex: 'M',
    phone_e164: '+919900112277', known_allergies: null,
    occupation: 'Small business owner', area: 'Yelahanka',
    primary_doctor_email: 'priya.suresh@even.in',
    active_problems: [
      { label: 'Chronic hepatitis B with compensated cirrhosis (Child-Pugh A)', since: '2019-04', status: 'active',
        current_meds: ['Tenofovir 300mg OD'] },
      { label: 'Esophageal varices grade 2 (no bleed)', since: '2024-07', status: 'controlled',
        current_meds: ['Propranolol 40mg BD'] },
    ],
    encounters: [
      { date: '2025-06-22', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly hep B + cirrhosis review. AFP + USG due.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 64, temp_c: 36.7, spo2: 98, weight_kg: 66, height_cm: 170, pain: 0 },
        exam_findings: 'No ascites. No oedema. Spleen tip palpable.',
        assessment_codes: ['B18.1', 'K74.6'],
        assessment_text: 'Stable. HCC surveillance + endoscopy due in 6mo.',
        rx_lines: [
          { generic: 'Tenofovir', brand: 'Tenof', strength: '300mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-10-04', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly. AFP 6.2, USG: nodular liver, no focal lesion.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 62, temp_c: 36.7, spo2: 98, weight_kg: 66, height_cm: 170, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['B18.1'],
        assessment_text: 'Stable.',
        rx_lines: [
          { generic: 'Tenofovir', brand: 'Tenof', strength: '300mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-01-12', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Surveillance endoscopy + AFP done.',
        vitals: { bp_sys: 120, bp_dia: 74, hr: 64, temp_c: 36.7, spo2: 98, weight_kg: 66, height_cm: 170, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['B18.1', 'I85.0'],
        assessment_text: 'Varices unchanged grade 2. AFP normal. Continue.',
        rx_lines: [
          { generic: 'Tenofovir', brand: 'Tenof', strength: '300mg', form: 'tablet', frequency: 'OD', duration_days: 180 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 180 },
        ],
        disposition: 'follow_up', follow_up_days: 180 },
      { date: '2026-04-18', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Stable. No black tarry stools, no abdominal distension.',
        vitals: { bp_sys: 118, bp_dia: 72, hr: 62, temp_c: 36.7, spo2: 98, weight_kg: 65, height_cm: 170, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['B18.1', 'K74.6'],
        assessment_text: 'Stable. AFP + USG every 6 months.',
        rx_lines: [
          { generic: 'Tenofovir', brand: 'Tenof', strength: '300mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-06-20', ordering_doctor_email: 'priya.suresh@even.in',
        orders: [
          { raw_text: 'HBV DNA + AFP + LFT + USG', canonical_key: 'hcc_surveillance', display_name: 'HCC Surveillance' },
        ],
        results: [
          { canonical_key: 'hbv_dna', display_name: 'HBV DNA', value_text: 'Undetectable', unit: 'IU/mL', reference_range: 'undetectable on therapy' },
          { canonical_key: 'afp', display_name: 'AFP', value_numeric: 5.8, unit: 'ng/mL', reference_range: '<10' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 32, unit: 'U/L', reference_range: '7-56' },
          { canonical_key: 'usg_liver', display_name: 'USG Liver', value_text: 'Coarse echotexture, nodular outline. No focal lesion. Spleen enlarged 14cm.', unit: '', reference_range: 'normal' },
        ] },
      { date: '2026-01-08', ordering_doctor_email: 'priya.suresh@even.in',
        orders: [
          { raw_text: 'Upper GI endoscopy + AFP + USG', canonical_key: 'cirrhosis_surveillance', display_name: 'Cirrhosis Surveillance' },
        ],
        results: [
          { canonical_key: 'upper_gi_endoscopy', display_name: 'Upper GI Endoscopy', value_text: 'Grade 2 esophageal varices, no red signs. Mild portal gastropathy.', unit: '', reference_range: 'normal' },
          { canonical_key: 'afp', display_name: 'AFP', value_numeric: 6.2, unit: 'ng/mL', reference_range: '<10' },
          { canonical_key: 'usg_liver', display_name: 'USG Liver', value_text: 'Stable. No new lesions.', unit: '', reference_range: 'normal' },
        ] },
    ],
    override_events: [],
  },

  // 40. Bhuvana Iyer — 67F — Banashankari — retired
  // Heart failure with reduced EF (HFrEF), on GDMT
  {
    mrn: 'EHRC-2026-040', name: 'Bhuvana Iyer', age_years: 67, sex: 'F',
    phone_e164: '+919844339922', known_allergies: null,
    occupation: 'Retired civil servant', area: 'Banashankari',
    primary_doctor_email: 'anika.iyer@even.in',
    active_problems: [
      { label: 'HFrEF (LVEF 30%, NYHA II)', since: '2024-11', status: 'active',
        current_meds: ['Sacubitril-Valsartan 49/51 BD', 'Bisoprolol 5mg OD', 'Spironolactone 25mg OD', 'Dapagliflozin 10mg OD'] },
      { label: 'Essential hypertension', since: '2015-06', status: 'controlled', current_meds: ['(via HF meds)'] },
      { label: 'Atrial fibrillation (paroxysmal)', since: '2024-11', status: 'controlled', current_meds: ['Apixaban 5mg BD'] },
    ],
    encounters: [
      { date: '2025-07-25', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly HF review. NYHA II. Walks ~300m on flat ground. No orthopnoea.',
        vitals: { bp_sys: 110, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 97, weight_kg: 62, height_cm: 156, pain: 0 },
        exam_findings: 'JVP not raised. No oedema. Lungs clear. S3 audible.',
        assessment_codes: ['I50.22'],
        assessment_text: 'HFrEF stable on quadruple therapy.',
        rx_lines: [
          { generic: 'Sacubitril + Valsartan', brand: 'Vymada', strength: '49+51mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Bisoprolol', brand: 'Concor', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Spironolactone', brand: 'Aldactone', strength: '25mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Dapagliflozin', brand: 'Forxiga', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-11-04', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly. Repeat echo done. EF 36%.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 70, temp_c: 36.7, spo2: 97, weight_kg: 62, height_cm: 156, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I50.22'],
        assessment_text: 'Improved EF on GDMT. Continue.',
        rx_lines: [
          { generic: 'Sacubitril + Valsartan', brand: 'Vymada', strength: '49+51mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Bisoprolol', brand: 'Concor', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Spironolactone', brand: 'Aldactone', strength: '25mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Dapagliflozin', brand: 'Forxiga', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-04', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly. Stable.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 68, temp_c: 36.7, spo2: 97, weight_kg: 62, height_cm: 156, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I50.22'],
        assessment_text: 'Stable.',
        rx_lines: [
          { generic: 'Sacubitril + Valsartan', brand: 'Vymada', strength: '49+51mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Bisoprolol', brand: 'Concor', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Spironolactone', brand: 'Aldactone', strength: '25mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Dapagliflozin', brand: 'Forxiga', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-05-04', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly. Doing well.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 70, temp_c: 36.7, spo2: 97, weight_kg: 62, height_cm: 156, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I50.22'],
        assessment_text: 'Stable. Next echo in 6mo.',
        rx_lines: [
          { generic: 'Sacubitril + Valsartan', brand: 'Vymada', strength: '49+51mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Bisoprolol', brand: 'Concor', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Spironolactone', brand: 'Aldactone', strength: '25mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Dapagliflozin', brand: 'Forxiga', strength: '10mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-22', ordering_doctor_email: 'anika.iyer@even.in',
        orders: [{ raw_text: 'NT-proBNP + Crea + electrolytes', canonical_key: 'hf_quarterly', display_name: 'HF Quarterly' }],
        results: [
          { canonical_key: 'nt_probnp', display_name: 'NT-proBNP', value_numeric: 1240, unit: 'pg/mL', reference_range: '<450 (age <55) · <900 (≥55)' },
          { canonical_key: 'creatinine', display_name: 'Creatinine', value_numeric: 1.1, unit: 'mg/dL', reference_range: '0.7-1.3' },
          { canonical_key: 'potassium', display_name: 'Potassium', value_numeric: 4.4, unit: 'mEq/L', reference_range: '3.5-5.0' },
        ] },
      { date: '2025-11-01', ordering_doctor_email: 'anika.iyer@even.in',
        orders: [
          { raw_text: 'Echo + NT-proBNP', canonical_key: 'hf_echo', display_name: 'HF Echo + BNP' },
        ],
        results: [
          { canonical_key: 'echo_lvef', display_name: 'Echo LVEF', value_numeric: 36, unit: '%', reference_range: '>55 normal' },
          { canonical_key: 'nt_probnp', display_name: 'NT-proBNP', value_numeric: 820, unit: 'pg/mL', reference_range: '<900' },
        ] },
      { date: '2026-05-02', ordering_doctor_email: 'anika.iyer@even.in',
        orders: [{ raw_text: 'NT-proBNP + Crea + electrolytes', canonical_key: 'hf_quarterly', display_name: 'HF Quarterly' }],
        results: [
          { canonical_key: 'nt_probnp', display_name: 'NT-proBNP', value_numeric: 680, unit: 'pg/mL', reference_range: '<900' },
          { canonical_key: 'creatinine', display_name: 'Creatinine', value_numeric: 1.1, unit: 'mg/dL', reference_range: '0.7-1.3' },
          { canonical_key: 'potassium', display_name: 'Potassium', value_numeric: 4.6, unit: 'mEq/L', reference_range: '3.5-5.0' },
        ] },
    ],
    override_events: [],
  },

  // 41. Sunil Bansal — 50M — Frazer Town — sales director
  // Type 1 diabetes (LADA), brittle control, ICU admit 4mo ago
  {
    mrn: 'EHRC-2026-041', name: 'Sunil Bansal', age_years: 50, sex: 'M',
    phone_e164: '+919900221177', known_allergies: null,
    occupation: 'Sales director', area: 'Frazer Town',
    primary_doctor_email: 'rajesh.murthy@even.in',
    active_problems: [
      { label: 'LADA (latent autoimmune diabetes in adults)', since: '2022-09', status: 'active',
        current_meds: ['Insulin Glargine 24u HS', 'Insulin Aspart sliding scale'] },
      { label: 'Diabetic ketoacidosis recovery (Jan 2026)', since: '2026-01', status: 'resolved' },
    ],
    encounters: [
      { date: '2025-08-12', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Diabetes follow-up'],
        cc_text: 'Quarterly. Glucose 100-180 range. Hypoglycaemia 2-3x/week early morning.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 78, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 174, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E10.9'],
        assessment_text: 'LADA — adjusting basal. CGM offered.',
        rx_lines: [
          { generic: 'Insulin Glargine', brand: 'Lantus', strength: '100u/mL', form: 'pen', frequency: 'HS', duration: '3 months', instructions: '20u HS, reduced from 24u.' },
          { generic: 'Insulin Aspart', brand: 'NovoRapid', strength: '100u/mL', form: 'pen', frequency: 'with meals', duration: '3 months', instructions: 'Sliding scale per glucose.' },
        ],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2026-01-04', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Diabetes follow-up'],
        cc_text: 'Admitted with DKA Jan 2 — caught a viral illness, missed insulin doses. Now discharged.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 88, temp_c: 36.7, spo2: 98, weight_kg: 65, height_cm: 174, pain: 0 },
        exam_findings: 'Improving. No focal signs.',
        assessment_codes: ['E10.10', 'E10.9'],
        assessment_text: 'Post-DKA. Sick-day rules reinforced.',
        rx_lines: [
          { generic: 'Insulin Glargine', brand: 'Lantus', strength: '100u/mL', form: 'pen', frequency: 'HS', duration: '3 months', instructions: '22u HS.' },
          { generic: 'Insulin Aspart', brand: 'NovoRapid', strength: '100u/mL', form: 'pen', frequency: 'with meals', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2026-02-14', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Diabetes follow-up'],
        cc_text: 'Recovering well. CGM data shared.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 66, height_cm: 174, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E10.9'],
        assessment_text: 'Glycaemic stability returning.',
        rx_lines: [
          { generic: 'Insulin Glargine', brand: 'Lantus', strength: '100u/mL', form: 'pen', frequency: 'HS', duration: '3 months' },
          { generic: 'Insulin Aspart', brand: 'NovoRapid', strength: '100u/mL', form: 'pen', frequency: 'with meals', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-05-08', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Diabetes follow-up'],
        cc_text: 'Quarterly. CGM TIR 72%. HbA1c 7.4.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 74, temp_c: 36.7, spo2: 98, weight_kg: 67, height_cm: 174, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E10.9'],
        assessment_text: 'Improving. Continue.',
        rx_lines: [
          { generic: 'Insulin Glargine', brand: 'Lantus', strength: '100u/mL', form: 'pen', frequency: 'HS', duration: '3 months' },
          { generic: 'Insulin Aspart', brand: 'NovoRapid', strength: '100u/mL', form: 'pen', frequency: 'with meals', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-08-10', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'HbA1c + GAD antibodies + C-peptide', canonical_key: 'lada_panel', display_name: 'LADA Panel' }],
        results: [
          { canonical_key: 'hba1c', display_name: 'HbA1c', value_numeric: 8.4, unit: '%', reference_range: '<5.7' },
          { canonical_key: 'gad65_antibody', display_name: 'GAD-65 Antibody', value_text: 'Positive', unit: '', reference_range: 'negative' },
          { canonical_key: 'c_peptide_fasting', display_name: 'Fasting C-peptide', value_numeric: 0.6, unit: 'ng/mL', reference_range: '1.1-4.4' },
        ] },
      { date: '2026-05-06', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'HbA1c', canonical_key: 'hba1c', display_name: 'HbA1c' }],
        results: [{ canonical_key: 'hba1c', display_name: 'HbA1c', value_numeric: 7.4, unit: '%', reference_range: '<5.7' }] },
    ],
    override_events: [],
  },

  // 42. Indira Reddy — 35F — Indiranagar — corporate exec
  // Recurrent miscarriage workup, antiphospholipid antibodies
  {
    mrn: 'EHRC-2026-042', name: 'Indira Reddy', age_years: 35, sex: 'F',
    phone_e164: '+919900663344', known_allergies: null,
    occupation: 'Corporate executive', area: 'Indiranagar',
    primary_doctor_email: 'aditya.sharma@even.in',
    active_problems: [
      { label: 'Antiphospholipid syndrome (with recurrent miscarriage)', since: '2025-09', status: 'active',
        current_meds: ['Aspirin 75mg OD', 'LMWH planned in next pregnancy'] },
    ],
    encounters: [
      { date: '2025-08-08', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Third miscarriage at 9 weeks. Wants workup.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 82, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 164, pain: 1 },
        exam_findings: 'No abdominal findings.',
        assessment_codes: ['N96'],
        assessment_text: 'Recurrent miscarriage workup.',
        rx_lines: [],
        disposition: 'diagnostics' },
      { date: '2025-09-22', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Workup back: anticardiolipin + lupus anticoagulant positive at 12-week repeat.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 78, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 164, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['D68.61'],
        assessment_text: 'APS confirmed. Start LDA. LMWH at next pregnancy confirmation.',
        rx_lines: [{ generic: 'Aspirin', brand: 'Ecosprin', strength: '75mg', form: 'tablet', frequency: 'OD', duration_days: 90, timing: 'after food' }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-12', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Routine.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 78, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 164, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['D68.61'],
        assessment_text: 'Continue LDA pre-conception.',
        rx_lines: [{ generic: 'Aspirin', brand: 'Ecosprin', strength: '75mg', form: 'tablet', frequency: 'OD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-08-25', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'APS panel + thrombophilia', canonical_key: 'aps_workup', display_name: 'APS Workup' }],
        results: [
          { canonical_key: 'lupus_anticoagulant', display_name: 'Lupus Anticoagulant', value_text: 'Positive', unit: '', reference_range: 'negative' },
          { canonical_key: 'anticardiolipin_igg', display_name: 'Anticardiolipin IgG', value_numeric: 48, unit: 'GPL', reference_range: '<10' },
          { canonical_key: 'antib2gp1_igg', display_name: 'Anti-β2GP1 IgG', value_numeric: 32, unit: 'U/mL', reference_range: '<20' },
        ] },
      { date: '2025-11-18', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'APS confirmatory (12-week)', canonical_key: 'aps_confirm', display_name: 'APS Confirmatory' }],
        results: [
          { canonical_key: 'lupus_anticoagulant', display_name: 'Lupus Anticoagulant', value_text: 'Positive', unit: '', reference_range: 'negative' },
          { canonical_key: 'anticardiolipin_igg', display_name: 'Anticardiolipin IgG', value_numeric: 52, unit: 'GPL', reference_range: '<10' },
        ] },
    ],
    override_events: [
      { date: '2025-09-22', doctor_email: 'aditya.sharma@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Antiphospholipid syndrome', status: 'active', note: 'Confirmed on 2 occasions 12 weeks apart.' } },
    ],
  },

  // 43. Mahesh Kowshik — 29M — Bellandur — startup founder
  // Schizophrenia, on second-gen antipsychotic, stable on community care
  {
    mrn: 'EHRC-2026-043', name: 'Mahesh Kowshik', age_years: 29, sex: 'M',
    phone_e164: '+919844223377', known_allergies: null,
    occupation: 'Startup founder', area: 'Bellandur',
    primary_doctor_email: 'ravi.kumar@even.in',
    active_problems: [
      { label: 'Schizophrenia, paranoid type', since: '2019-04', status: 'controlled',
        current_meds: ['Olanzapine 10mg HS'] },
      { label: 'Olanzapine-induced metabolic syndrome', since: '2022-08', status: 'active',
        current_meds: ['Metformin 500mg BD'] },
    ],
    encounters: [
      { date: '2025-07-22', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety'],
        cc_text: 'Quarterly review. Stable. Working. No psychotic symptoms in 18 months.',
        vitals: { bp_sys: 124, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 86, height_cm: 176, pain: 0 },
        exam_findings: 'Euthymic. No psychotic features.',
        assessment_codes: ['F20.0'],
        assessment_text: 'Schizophrenia in remission. Metabolic side-effects monitored.',
        rx_lines: [
          { generic: 'Olanzapine', brand: 'Oleanz', strength: '10mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-11-04', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety', 'Lab review'],
        cc_text: 'Stable. HbA1c rising on olanzapine.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 87, height_cm: 176, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['F20.0'],
        assessment_text: 'Add metabolic intervention. Discussed switch to less metabogenic agent.',
        rx_lines: [
          { generic: 'Olanzapine', brand: 'Oleanz', strength: '10mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-12', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety'],
        cc_text: 'Continued stability.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 87, height_cm: 176, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['F20.0'],
        assessment_text: 'Stable.',
        rx_lines: [
          { generic: 'Olanzapine', brand: 'Oleanz', strength: '10mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-11-01', ordering_doctor_email: 'ravi.kumar@even.in',
        orders: [{ raw_text: 'HbA1c + Lipid + LFT', canonical_key: 'antipsychotic_monitoring', display_name: 'Antipsychotic Monitoring' }],
        results: [
          { canonical_key: 'hba1c', display_name: 'HbA1c', value_numeric: 6.4, unit: '%', reference_range: '<5.7' },
          { canonical_key: 'triglycerides', display_name: 'Triglycerides', value_numeric: 198, unit: 'mg/dL', reference_range: '<150' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 38, unit: 'U/L', reference_range: '7-56' },
        ] },
    ],
    override_events: [],
  },
];
