/**
 * v2.0.0 seed — patient stories batch 6 (8 new patients).
 * EHRC-2026-028 through 035 — new patients filling clinical gaps.
 */
import type { SeedPatient } from './types';

export const PATIENTS_BATCH_6: SeedPatient[] = [
  // 28. Hari Krishna — 68M — Basavanagudi — retired professor
  // Idiopathic Parkinson's, mild cognitive impairment, falls risk
  {
    mrn: 'EHRC-2026-028', name: 'Hari Krishna', age_years: 68, sex: 'M',
    phone_e164: '+919845443322', known_allergies: null,
    occupation: 'Retired professor of physics', area: 'Basavanagudi',
    primary_doctor_email: 'vinay.bhardwaj@even.in',
    active_problems: [
      { label: 'Idiopathic Parkinson disease (Hoehn-Yahr II)', since: '2023-05', status: 'active',
        current_meds: ['Levodopa-Carbidopa 100/25 TDS', 'Rasagiline 1mg OD'] },
      { label: 'Mild cognitive impairment', since: '2025-09', status: 'active' },
      { label: 'Essential hypertension', since: '2018-04', status: 'controlled',
        current_meds: ['Amlodipine 5mg OD'] },
    ],
    encounters: [
      { date: '2025-07-18', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Quarterly Parkinson follow-up. Rest tremor right hand mildly worse. Wife reports occasional word-finding hesitation.',
        vitals: { bp_sys: 134, bp_dia: 80, hr: 68, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 170, pain: 1 },
        exam_findings: 'Resting tremor R hand, mild rigidity bilateral UE. Bradykinesia. UPDRS-III 22. Gait normal speed, mild stooped posture.',
        assessment_codes: ['G20'],
        assessment_text: 'PD H-Y II. Adding Rasagiline as adjunct.',
        rx_lines: [
          { generic: 'Levodopa + Carbidopa', brand: 'Syndopa', strength: '100mg+25mg', form: 'tablet', frequency: 'TDS', duration_days: 90 },
          { generic: 'Rasagiline', brand: 'Azilect', strength: '1mg', form: 'tablet', frequency: 'OD', duration_days: 90, instructions: 'New adjunct.' },
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-10-10', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Dizziness'],
        cc_text: 'Postural giddiness occasionally on standing. No falls. Wife reports MoCA-style concerns continue.',
        vitals: { bp_sys: 138, bp_dia: 82, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 170, pain: 0 },
        exam_findings: 'Orthostatic drop 20mmHg systolic. UPDRS-III 20 — modestly improved. MoCA 24/30.',
        assessment_codes: ['G20', 'F06.7'],
        assessment_text: 'PD with orthostatic hypotension, MCI. Counsel re: standing slowly + hydration. Document MCI.',
        rx_lines: [
          { generic: 'Levodopa + Carbidopa', brand: 'Syndopa', strength: '100mg+25mg', form: 'tablet', frequency: 'TDS', duration_days: 90 },
          { generic: 'Rasagiline', brand: 'Azilect', strength: '1mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-01-20', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Routine. Tremor stable. Sleep poor — REM behavior episodes per wife.',
        vitals: { bp_sys: 132, bp_dia: 78, hr: 68, temp_c: 36.7, spo2: 98, weight_kg: 67, height_cm: 170, pain: 0 },
        exam_findings: 'UPDRS-III 22. Mild postural instability — recovery on pull test 2-step.',
        assessment_codes: ['G20', 'G47.52'],
        assessment_text: 'RBD likely. Add low-dose Clonazepam.',
        rx_lines: [
          { generic: 'Levodopa + Carbidopa', brand: 'Syndopa', strength: '100mg+25mg', form: 'tablet', frequency: 'TDS', duration_days: 90 },
          { generic: 'Rasagiline', brand: 'Azilect', strength: '1mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Clonazepam', brand: 'Clonotril', strength: '0.5mg', form: 'tablet', frequency: 'HS', duration_days: 30 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-04-22', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Routine. RBD better on Clonazepam. Mild dyskinesia after late dose.',
        vitals: { bp_sys: 128, bp_dia: 76, hr: 68, temp_c: 36.7, spo2: 98, weight_kg: 67, height_cm: 170, pain: 0 },
        exam_findings: 'Mild choreiform dyskinesia head, mid-dose. UPDRS-III 20.',
        assessment_codes: ['G20'],
        assessment_text: 'Mild end-of-dose dyskinesia. Adjusting interval, adding Entacapone.',
        rx_lines: [
          { generic: 'Levodopa + Carbidopa + Entacapone', brand: 'Stalevo', strength: '100/25/200mg', form: 'tablet', frequency: 'TDS', duration_days: 90 },
          { generic: 'Rasagiline', brand: 'Azilect', strength: '1mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Clonazepam', brand: 'Clonotril', strength: '0.5mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-10-08', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'MoCA + Routine bloods', canonical_key: 'cognitive_panel', display_name: 'Cognitive Screen + Routine' }],
        results: [
          { canonical_key: 'moca', display_name: 'MoCA', value_numeric: 24, unit: '/30', reference_range: '≥26 normal · 18-25 MCI' },
          { canonical_key: 'b12', display_name: 'Vitamin B12', value_numeric: 312, unit: 'pg/mL', reference_range: '200-900' },
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 2.4, unit: 'µIU/mL', reference_range: '0.4-4.5' },
        ] },
    ],
    override_events: [
      { date: '2025-10-10', doctor_email: 'vinay.bhardwaj@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Mild cognitive impairment', status: 'active', note: 'MoCA 24/30. Wife concerned. Will repeat in 6mo.' } },
    ],
  },

  // 29. Pratibha Kashyap — 29F — Vasanth Nagar — software architect
  // Hypothyroid in fertility workup
  {
    mrn: 'EHRC-2026-029', name: 'Pratibha Kashyap', age_years: 29, sex: 'F',
    phone_e164: '+919900223344', known_allergies: 'Nuts (anaphylaxis as child)',
    occupation: 'Software architect', area: 'Vasanth Nagar',
    primary_doctor_email: 'rajesh.murthy@even.in',
    active_problems: [
      { label: 'Subclinical hypothyroidism, fertility-relevant', since: '2025-11', status: 'controlled',
        current_meds: ['Levothyroxine 50mcg OD'] },
      { label: 'Primary infertility (workup ongoing)', since: '2025-09', status: 'active' },
    ],
    encounters: [
      { date: '2025-09-04', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Trying to conceive for 14 months, no success. Cycles regular.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 60, height_cm: 164, pain: 0 },
        exam_findings: 'BMI 22.3. Normal.',
        assessment_codes: ['N97.9'],
        assessment_text: 'Primary infertility workup.',
        rx_lines: [], disposition: 'diagnostics' },
      { date: '2025-11-12', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'TSH 5.6 — subclinical hypothyroid impacting fertility.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 60, height_cm: 164, pain: 0 },
        exam_findings: 'No goitre.',
        assessment_codes: ['E03.9', 'N97.9'],
        assessment_text: 'Subclinical hypothyroidism with anti-TPO+ in fertility workup. Treat to TSH <2.5.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2026-01-22', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Thyroid follow-up'],
        cc_text: 'TSH 2.1 — at target.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 60, height_cm: 164, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E03.9'],
        assessment_text: 'At target. Continue. OBG to optimize fertility plan.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-04-30', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Thyroid follow-up'],
        cc_text: 'Quarterly review. Currently doing IUI cycle. TSH on target.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 61, height_cm: 164, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E03.9'],
        assessment_text: 'Stable.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-11-08', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'TSH + Anti-TPO + Prolactin', canonical_key: 'fertility_thyroid', display_name: 'Fertility Thyroid Panel' }],
        results: [
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 5.6, unit: 'µIU/mL', reference_range: '0.4-4.5' },
          { canonical_key: 'anti_tpo', display_name: 'Anti-TPO', value_numeric: 142, unit: 'IU/mL', reference_range: '<35' },
          { canonical_key: 'prolactin', display_name: 'Prolactin', value_numeric: 18, unit: 'ng/mL', reference_range: '4-23' },
        ] },
      { date: '2026-01-19', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'TSH', canonical_key: 'tsh', display_name: 'TSH' }],
        results: [{ canonical_key: 'tsh', display_name: 'TSH', value_numeric: 2.1, unit: 'µIU/mL', reference_range: '0.4-4.5' }] },
      { date: '2026-04-27', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'TSH', canonical_key: 'tsh', display_name: 'TSH' }],
        results: [{ canonical_key: 'tsh', display_name: 'TSH', value_numeric: 1.9, unit: 'µIU/mL', reference_range: '0.4-4.5' }] },
    ],
    override_events: [],
  },

  // 30. Govindaraju Murthy — 74M — Padmanabha Nagar — retired
  // Post-stroke (right MCA, 2024), residual left hemiparesis, on warfarin for AF
  {
    mrn: 'EHRC-2026-030', name: 'Govindaraju Murthy', age_years: 74, sex: 'M',
    phone_e164: '+919845558899', known_allergies: 'NSAIDs (GI bleed history)',
    occupation: 'Retired bank officer', area: 'Padmanabha Nagar',
    primary_doctor_email: 'vinay.bhardwaj@even.in',
    active_problems: [
      { label: 'Right MCA territory ischaemic stroke (Mar 2024) with residual left hemiparesis', since: '2024-03', status: 'active' },
      { label: 'Atrial fibrillation (paroxysmal)', since: '2024-03', status: 'active', current_meds: ['Warfarin 3mg OD', 'Diltiazem 90mg BD'] },
      { label: 'Essential hypertension', since: '2008-06', status: 'controlled', current_meds: ['Telmisartan 80mg OD'] },
      { label: 'Type 2 diabetes mellitus', since: '2015-09', status: 'controlled', current_meds: ['Metformin 1g BD'] },
    ],
    encounters: [
      { date: '2025-08-04', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Lab review', 'BP follow-up'],
        cc_text: 'Quarterly post-stroke review. Walks with cane, occasional shuffle gait. INR review.',
        vitals: { bp_sys: 138, bp_dia: 78, hr: 72, temp_c: 36.7, spo2: 97, weight_kg: 64, height_cm: 168, pain: 1 },
        exam_findings: 'Power L UL 4/5, L LL 4+/5. Spasticity mild bilateral. UMN signs L side. Speech mildly dysarthric.',
        assessment_codes: ['I69.3', 'I48.0'],
        assessment_text: 'Post-stroke stable. INR 2.4 — at target.',
        rx_lines: [
          { generic: 'Warfarin', brand: 'Warf', strength: '3mg', form: 'tablet', frequency: 'OD', duration_days: 90, timing: '5pm', instructions: 'Consistent leafy greens intake.' },
          { generic: 'Diltiazem', brand: 'Dilzem', strength: '90mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Telmisartan', brand: 'Telma', strength: '80mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '1g', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Atorvastatin', brand: 'Atorva', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 30 },
      { date: '2025-11-04', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Quarterly. Stable.',
        vitals: { bp_sys: 134, bp_dia: 76, hr: 70, temp_c: 36.7, spo2: 97, weight_kg: 64, height_cm: 168, pain: 0 },
        exam_findings: 'Unchanged.',
        assessment_codes: ['I69.3', 'I48.0'],
        assessment_text: 'INR 2.6 — at target.',
        rx_lines: [
          { generic: 'Warfarin', brand: 'Warf', strength: '3mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Diltiazem', brand: 'Dilzem', strength: '90mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Telmisartan', brand: 'Telma', strength: '80mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '1g', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Atorvastatin', brand: 'Atorva', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-09', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'New-onset headache for 5 days. Wife concerned re: bleed risk on warfarin.',
        vitals: { bp_sys: 152, bp_dia: 88, hr: 76, temp_c: 36.7, spo2: 97, weight_kg: 63, height_cm: 168, pain: 5 },
        exam_findings: 'No new neuro deficit. BP elevated.',
        assessment_codes: ['G44.2'],
        assessment_text: 'BP-related headache likely; CT head as safety check given warfarin.',
        rx_lines: [
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'TDS PRN', duration_days: 5 },
        ],
        disposition: 'diagnostics' },
      { date: '2026-02-12', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'CT normal — no haemorrhage. BP improved.',
        vitals: { bp_sys: 142, bp_dia: 82, hr: 74, temp_c: 36.7, spo2: 97, weight_kg: 63, height_cm: 168, pain: 1 },
        exam_findings: 'Stable.',
        assessment_codes: ['I69.3'],
        assessment_text: 'CT clear. Continue.',
        rx_lines: [
          { generic: 'Warfarin', brand: 'Warf', strength: '3mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Telmisartan', brand: 'Telma', strength: '80mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90, instructions: 'Added for BP buffer.' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-08-02', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'INR + Crea + HbA1c', canonical_key: 'stroke_quarterly', display_name: 'Stroke Quarterly Panel' }],
        results: [
          { canonical_key: 'inr', display_name: 'INR', value_numeric: 2.4, unit: '', reference_range: '2.0-3.0 (AF)' },
          { canonical_key: 'creatinine', display_name: 'Creatinine', value_numeric: 1.2, unit: 'mg/dL', reference_range: '0.7-1.3' },
          { canonical_key: 'hba1c', display_name: 'HbA1c', value_numeric: 6.9, unit: '%', reference_range: '<5.7' },
        ] },
      { date: '2025-11-01', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'INR', canonical_key: 'inr', display_name: 'INR' }],
        results: [{ canonical_key: 'inr', display_name: 'INR', value_numeric: 2.6, unit: '', reference_range: '2.0-3.0 (AF)' }] },
      { date: '2026-02-10', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [
          { raw_text: 'CT head non-contrast', canonical_key: 'ct_head', display_name: 'CT Head' },
          { raw_text: 'INR', canonical_key: 'inr', display_name: 'INR' },
        ],
        results: [
          { canonical_key: 'ct_head', display_name: 'CT Head', value_text: 'Old right MCA infarct, gliosis. No acute haemorrhage. Mild small vessel disease.', unit: '', reference_range: 'normal' },
          { canonical_key: 'inr', display_name: 'INR', value_numeric: 2.8, unit: '', reference_range: '2.0-3.0' },
        ] },
    ],
    override_events: [],
  },

  // 31. Bhavana Hegde — 16F — Indiranagar — student
  // Newly diagnosed asthma, allergic
  {
    mrn: 'EHRC-2026-031', name: 'Bhavana Hegde', age_years: 16, sex: 'F',
    phone_e164: '+919900334455', known_allergies: 'Dust, pollen',
    occupation: '11th grade student', area: 'Indiranagar',
    primary_doctor_email: 'lakshmi.naidu@even.in',
    active_problems: [
      { label: 'Bronchial asthma — mild persistent', since: '2025-09', status: 'controlled',
        current_meds: ['Budesonide-Formoterol inhaler BD', 'Salbutamol PRN'] },
      { label: 'Allergic rhinitis', since: '2014', status: 'active', current_meds: ['Fluticasone nasal'] },
    ],
    encounters: [
      { date: '2025-09-15', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Cough', 'Asthma review'],
        cc_text: 'Recurrent night cough x 3 months, wheezing during sports.',
        vitals: { bp_sys: 108, bp_dia: 68, hr: 88, rr: 20, temp_c: 36.7, spo2: 97, weight_kg: 48, height_cm: 161, pain: 0 },
        exam_findings: 'Mild expiratory wheeze bilateral.',
        assessment_codes: ['J45.9'],
        assessment_text: 'Asthma — initiate ICS-LABA.',
        rx_lines: [
          { generic: 'Budesonide + Formoterol', brand: 'Foracort', strength: '200mcg+6mcg', form: 'inhaler', frequency: 'BD', duration_days: 60, instructions: 'Rinse mouth after.' },
          { generic: 'Salbutamol', brand: 'Asthalin', strength: '100mcg', form: 'inhaler', frequency: 'PRN', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2025-11-22', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Asthma review'],
        cc_text: 'Symptoms much better, no nocturnal cough, sports tolerated. Peak flow personal best documented.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 80, rr: 16, temp_c: 36.7, spo2: 99, weight_kg: 49, height_cm: 161, pain: 0 },
        exam_findings: 'Chest clear.',
        assessment_codes: ['J45.9'],
        assessment_text: 'Well-controlled. Continue.',
        rx_lines: [
          { generic: 'Budesonide + Formoterol', brand: 'Foracort', strength: '200mcg+6mcg', form: 'inhaler', frequency: 'BD', duration_days: 90 },
          { generic: 'Salbutamol', brand: 'Asthalin', strength: '100mcg', form: 'inhaler', frequency: 'PRN', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-03-04', doctor_email: 'meera.pillai@even.in', room_name: 'OPD-9',
        cc_chips: ['Rash / itching'],
        cc_text: 'New facial acne over past 3 months. Worsening with exam stress.',
        vitals: { bp_sys: 108, bp_dia: 70, hr: 78, temp_c: 36.7, spo2: 99, weight_kg: 49, height_cm: 161, pain: 0 },
        exam_findings: 'Comedones + papules on cheeks and forehead. Mild grade.',
        assessment_codes: ['L70.0'],
        assessment_text: 'Acne vulgaris, mild. Topical retinoid + benzoyl peroxide.',
        rx_lines: [
          { generic: 'Adapalene', brand: 'Differin', strength: '0.1%', form: 'gel', frequency: 'HS', duration_days: 60 },
          { generic: 'Benzoyl peroxide', brand: 'Persol-BPO', strength: '2.5%', form: 'gel', frequency: 'OD', duration_days: 60 },
        ],
        disposition: 'follow_up', follow_up_days: 60 },
    ],
    lab_cycles: [
      { date: '2025-09-12', ordering_doctor_email: 'lakshmi.naidu@even.in',
        orders: [
          { raw_text: 'Spirometry', canonical_key: 'spirometry', display_name: 'Spirometry' },
          { raw_text: 'Total IgE', canonical_key: 'total_ige', display_name: 'Total IgE' },
        ],
        results: [
          { canonical_key: 'spirometry_fev1_pct', display_name: 'FEV1 % predicted', value_numeric: 88, unit: '%', reference_range: '>80% normal' },
          { canonical_key: 'spirometry_bd_response', display_name: 'Post-BD reversibility', value_text: '+18% increase in FEV1', unit: '', reference_range: '>12% suggests asthma' },
          { canonical_key: 'total_ige', display_name: 'Total IgE', value_numeric: 312, unit: 'IU/mL', reference_range: '<100' },
        ] },
    ],
    override_events: [],
  },

  // 32. Saraswati Bhat — 78F — Vijayanagar — retired
  // Recent fragility fracture (wrist), osteoporosis, HTN, DM
  {
    mrn: 'EHRC-2026-032', name: 'Saraswati Bhat', age_years: 78, sex: 'F',
    phone_e164: '+919844223344', known_allergies: null,
    occupation: 'Retired', area: 'Vijayanagar',
    primary_doctor_email: 'karthik.reddy@even.in',
    active_problems: [
      { label: 'Osteoporosis with fragility fracture (left Colles fracture, Aug 2025)', since: '2024-04', status: 'active',
        current_meds: ['Alendronate 70mg weekly', 'Calcium + Vit D3'] },
      { label: 'Type 2 diabetes mellitus', since: '2014-03', status: 'controlled', current_meds: ['Metformin 500mg BD'] },
      { label: 'Hypertension', since: '2010-08', status: 'controlled', current_meds: ['Amlodipine 5mg OD'] },
    ],
    encounters: [
      { date: '2025-08-22', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Fell at home, wrist pain + swelling.',
        vitals: { bp_sys: 142, bp_dia: 78, hr: 86, temp_c: 36.7, spo2: 97, weight_kg: 54, height_cm: 152, pain: 8 },
        exam_findings: 'Left wrist dinner-fork deformity. X-ray confirms Colles fracture.',
        assessment_codes: ['S52.5'],
        assessment_text: 'Colles fracture — closed reduction + cast.',
        rx_lines: [
          { generic: 'Tramadol', brand: 'Tramazac', strength: '50mg', form: 'tablet', frequency: 'PRN', duration: '5 days' },
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'TDS', duration_days: 7 },
        ],
        disposition: 'follow_up', follow_up_days: 7 },
      { date: '2025-09-30', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Cast off. Wrist movement gradually returning. DEXA scan due given fragility fracture.',
        vitals: { bp_sys: 138, bp_dia: 76, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 54, height_cm: 152, pain: 2 },
        exam_findings: 'Wrist alignment satisfactory. Mild stiffness.',
        assessment_codes: ['M80.0'],
        assessment_text: 'Post-Colles. Osteoporosis workup.',
        rx_lines: [
          { generic: 'Calcium + Vit D3', brand: 'Shelcal', strength: '500mg+250IU', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Cholecalciferol', brand: 'Calcirol', strength: '60000 IU', form: 'sachet', frequency: 'weekly', duration: '8 weeks' },
        ],
        disposition: 'diagnostics' },
      { date: '2025-10-25', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Lab review'],
        cc_text: 'DEXA T-score -3.2 lumbar — osteoporosis.',
        vitals: { bp_sys: 136, bp_dia: 76, hr: 74, temp_c: 36.7, spo2: 98, weight_kg: 54, height_cm: 152, pain: 1 },
        exam_findings: 'Stable.',
        assessment_codes: ['M81.0'],
        assessment_text: 'Osteoporosis. Bisphosphonate start.',
        rx_lines: [
          { generic: 'Alendronate', brand: 'Fosamax', strength: '70mg', form: 'tablet', frequency: 'weekly', duration: '3 months', instructions: 'Empty stomach, sit upright 30 min.' },
          { generic: 'Calcium + Vit D3', brand: 'Shelcal', strength: '500mg+250IU', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-04', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up', 'Diabetes follow-up'],
        cc_text: 'Quarterly review. Tolerating alendronate, no GI issues.',
        vitals: { bp_sys: 134, bp_dia: 76, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 54, height_cm: 152, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I10', 'E11.9', 'M81.0'],
        assessment_text: 'All stable.',
        rx_lines: [
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Alendronate', brand: 'Fosamax', strength: '70mg', form: 'tablet', frequency: 'weekly', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-10-22', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [
          { raw_text: 'DEXA scan + Vit D + Calcium', canonical_key: 'osteoporosis_panel', display_name: 'Osteoporosis Workup' },
        ],
        results: [
          { canonical_key: 'dexa_lumbar_tscore', display_name: 'DEXA T-score Lumbar', value_numeric: -3.2, unit: 'SD', reference_range: '> -1.0 normal' },
          { canonical_key: 'dexa_femoral_tscore', display_name: 'DEXA T-score Femoral', value_numeric: -2.6, unit: 'SD', reference_range: '> -1.0 normal' },
          { canonical_key: 'vitamin_d', display_name: 'Vitamin D', value_numeric: 12, unit: 'ng/mL', reference_range: '30-100' },
          { canonical_key: 'serum_calcium', display_name: 'Calcium', value_numeric: 8.8, unit: 'mg/dL', reference_range: '8.5-10.5' },
        ] },
    ],
    override_events: [
      { date: '2025-10-25', doctor_email: 'karthik.reddy@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Osteoporosis with fragility fracture', status: 'active', note: 'T-score -3.2 + Colles fracture. High fracture risk.' } },
    ],
  },

  // 33. Tarun Bharadwaj — 38M — Rajajinagar — chef
  // Recent acute viral hepatitis A, recovering
  {
    mrn: 'EHRC-2026-033', name: 'Tarun Bharadwaj', age_years: 38, sex: 'M',
    phone_e164: '+919900445599', known_allergies: null,
    occupation: 'Chef', area: 'Rajajinagar',
    primary_doctor_email: 'priya.suresh@even.in',
    active_problems: [
      { label: 'Acute viral hepatitis A — recovering', since: '2026-04', status: 'active' },
    ],
    encounters: [
      { date: '2026-04-08', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Fever', 'Abdominal pain'],
        cc_text: 'Fever, nausea, RUQ pain, dark urine x 5 days.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 92, temp_c: 38.2, spo2: 99, weight_kg: 72, height_cm: 175, pain: 4 },
        exam_findings: 'Mild scleral icterus. Hepatomegaly tender.',
        assessment_codes: ['B15.9'],
        assessment_text: 'Acute hepatitis — likely viral. Send hep panel.',
        rx_lines: [
          { generic: 'Paracetamol', brand: 'Crocin', strength: '500mg', form: 'tablet', frequency: 'TDS PRN', duration_days: 5, instructions: 'Max 2g/day given hepatitis.' },
          { generic: 'Ondansetron', brand: 'Emeset', strength: '4mg', form: 'tablet', frequency: 'PRN', duration: '7 days' },
        ],
        disposition: 'diagnostics' },
      { date: '2026-04-15', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Hepatitis A IgM positive. Liver enzymes high.',
        vitals: { bp_sys: 116, bp_dia: 72, hr: 80, temp_c: 36.9, spo2: 99, weight_kg: 71, height_cm: 175, pain: 3 },
        exam_findings: 'Scleral icterus less. Liver tender mildly.',
        assessment_codes: ['B15.9'],
        assessment_text: 'Acute hep A confirmed. Conservative. Rest + hydration.',
        rx_lines: [
          { generic: 'Ursodeoxycholic acid', brand: 'Udiliv', strength: '300mg', form: 'tablet', frequency: 'BD', duration_days: 30 },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2026-04-29', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Lab review'],
        cc_text: 'Resolving. Energy returning. Icterus gone.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 71, height_cm: 175, pain: 1 },
        exam_findings: 'No icterus. Liver not palpable.',
        assessment_codes: ['B15.9'],
        assessment_text: 'Recovering well.',
        rx_lines: [{ generic: 'Ursodeoxycholic acid', brand: 'Udiliv', strength: '300mg', form: 'tablet', frequency: 'BD', duration_days: 30 }],
        disposition: 'follow_up', follow_up_days: 30,
        handoff_note: 'Food handler — clearance certificate needed before return to chef duties. LFT normalisation first.' },
    ],
    lab_cycles: [
      { date: '2026-04-09', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [
          { raw_text: 'LFT + Hepatitis viral panel', canonical_key: 'hepatitis_panel', display_name: 'Hepatitis Panel' },
        ],
        results: [
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 1240, unit: 'U/L', reference_range: '7-56', is_critical: true },
          { canonical_key: 'ast', display_name: 'AST', value_numeric: 980, unit: 'U/L', reference_range: '10-40', is_critical: true },
          { canonical_key: 'total_bilirubin', display_name: 'Total Bilirubin', value_numeric: 4.8, unit: 'mg/dL', reference_range: '<1.2' },
          { canonical_key: 'hav_igm', display_name: 'Anti-HAV IgM', value_text: 'Positive', unit: '', reference_range: 'negative' },
          { canonical_key: 'hbsag', display_name: 'HBsAg', value_text: 'Negative', unit: '', reference_range: 'negative' },
          { canonical_key: 'anti_hcv', display_name: 'Anti-HCV', value_text: 'Negative', unit: '', reference_range: 'negative' },
        ] },
      { date: '2026-04-27', ordering_doctor_email: 'priya.suresh@even.in',
        orders: [{ raw_text: 'LFT recheck', canonical_key: 'lft', display_name: 'LFT recheck' }],
        results: [
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 142, unit: 'U/L', reference_range: '7-56' },
          { canonical_key: 'ast', display_name: 'AST', value_numeric: 98, unit: 'U/L', reference_range: '10-40' },
          { canonical_key: 'total_bilirubin', display_name: 'Total Bilirubin', value_numeric: 1.4, unit: 'mg/dL', reference_range: '<1.2' },
        ] },
    ],
    override_events: [],
  },

  // 34. Sneha Kulkarni — 41F — Sahakar Nagar — corporate consultant
  // Bipolar II disorder, on lithium long-term
  {
    mrn: 'EHRC-2026-034', name: 'Sneha Kulkarni', age_years: 41, sex: 'F',
    phone_e164: '+919844667788', known_allergies: null,
    occupation: 'Corporate consultant', area: 'Sahakar Nagar',
    primary_doctor_email: 'ravi.kumar@even.in',
    active_problems: [
      { label: 'Bipolar II disorder', since: '2014-08', status: 'controlled',
        current_meds: ['Lithium carbonate 600mg HS', 'Quetiapine 50mg HS'] },
      { label: 'Lithium-induced subclinical hypothyroidism', since: '2019-03', status: 'controlled',
        current_meds: ['Levothyroxine 25mcg OD'] },
    ],
    encounters: [
      { date: '2025-07-15', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety'],
        cc_text: 'Quarterly psychiatric review. Mood stable for 8 months.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 162, pain: 0 },
        exam_findings: 'Euthymic. Affect appropriate. Insight intact.',
        assessment_codes: ['F31.81'],
        assessment_text: 'Bipolar II in remission. Continue.',
        rx_lines: [
          { generic: 'Lithium carbonate', brand: 'Lithosun', strength: '600mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Quetiapine', brand: 'Seroquel', strength: '50mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Levothyroxine', brand: 'Eltroxin', strength: '25mcg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-10-22', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety', 'Lab review'],
        cc_text: 'Mild hypomania prodrome over past week — irritable, sleep cut to 4-5hr. Lithium level due.',
        vitals: { bp_sys: 120, bp_dia: 76, hr: 78, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 162, pain: 0 },
        exam_findings: 'Pressured speech mild. PHQ-9 6, YMRS 14.',
        assessment_codes: ['F31.81'],
        assessment_text: 'Early hypomania prodrome. Lithium level 0.6 — could increase to 0.8 target.',
        rx_lines: [
          { generic: 'Lithium carbonate', brand: 'Lithosun', strength: '800mg', form: 'tablet', frequency: 'HS', duration_days: 30, instructions: 'Up-titrated from 600mg.' },
          { generic: 'Quetiapine', brand: 'Seroquel', strength: '100mg', form: 'tablet', frequency: 'HS', duration_days: 14, instructions: 'Stress-dose temporarily.' },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2025-12-04', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Anxiety'],
        cc_text: 'Settled. Sleep restored. Mood euthymic.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 162, pain: 0 },
        exam_findings: 'Euthymic.',
        assessment_codes: ['F31.81'],
        assessment_text: 'Recovered. Continue current regimen.',
        rx_lines: [
          { generic: 'Lithium carbonate', brand: 'Lithosun', strength: '800mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Quetiapine', brand: 'Seroquel', strength: '50mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-03-12', doctor_email: 'ravi.kumar@even.in', room_name: 'OPD-10',
        cc_chips: ['Lab review'],
        cc_text: 'Routine. Stable.',
        vitals: { bp_sys: 116, bp_dia: 72, hr: 70, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 162, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['F31.81'],
        assessment_text: 'Stable. Lithium level 0.8.',
        rx_lines: [
          { generic: 'Lithium carbonate', brand: 'Lithosun', strength: '800mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Quetiapine', brand: 'Seroquel', strength: '50mg', form: 'tablet', frequency: 'HS', duration_days: 90 },
          { generic: 'Levothyroxine', brand: 'Eltroxin', strength: '25mcg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-12', ordering_doctor_email: 'ravi.kumar@even.in',
        orders: [{ raw_text: 'Lithium level + TSH + Crea', canonical_key: 'lithium_panel', display_name: 'Lithium Monitoring' }],
        results: [
          { canonical_key: 'lithium_level', display_name: 'Lithium Level', value_numeric: 0.7, unit: 'mEq/L', reference_range: '0.6-1.2 (therapeutic)' },
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 3.4, unit: 'µIU/mL', reference_range: '0.4-4.5' },
          { canonical_key: 'creatinine', display_name: 'Creatinine', value_numeric: 0.9, unit: 'mg/dL', reference_range: '0.7-1.3' },
        ] },
      { date: '2025-10-20', ordering_doctor_email: 'ravi.kumar@even.in',
        orders: [{ raw_text: 'Lithium level', canonical_key: 'lithium_level', display_name: 'Lithium Level' }],
        results: [{ canonical_key: 'lithium_level', display_name: 'Lithium Level', value_numeric: 0.6, unit: 'mEq/L', reference_range: '0.6-1.2' }] },
      { date: '2026-03-10', ordering_doctor_email: 'ravi.kumar@even.in',
        orders: [{ raw_text: 'Lithium level + TSH', canonical_key: 'lithium_panel', display_name: 'Lithium Quarterly' }],
        results: [
          { canonical_key: 'lithium_level', display_name: 'Lithium Level', value_numeric: 0.8, unit: 'mEq/L', reference_range: '0.6-1.2' },
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 3.8, unit: 'µIU/mL', reference_range: '0.4-4.5' },
        ] },
    ],
    override_events: [],
  },

  // 35. Aakash Bose — 22M — Yelahanka — engineering student
  // Sports-related ACL injury, recent surgery, rehab
  {
    mrn: 'EHRC-2026-035', name: 'Aakash Bose', age_years: 22, sex: 'M',
    phone_e164: '+919900889977', known_allergies: null,
    occupation: 'Engineering student', area: 'Yelahanka',
    primary_doctor_email: 'karthik.reddy@even.in',
    active_problems: [
      { label: 'Left ACL reconstruction (post-op, Mar 2026)', since: '2026-03', status: 'active' },
    ],
    encounters: [
      { date: '2026-02-08', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Football injury 4 weeks ago — twisted left knee landing from jump. Felt pop. Swelling subsided but knee gives way occasionally.',
        vitals: { bp_sys: 124, bp_dia: 76, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 72, height_cm: 178, pain: 4 },
        exam_findings: 'Lachman positive. Anterior drawer positive. No effusion at this point.',
        assessment_codes: ['S83.5'],
        assessment_text: 'Clinical ACL tear. MRI to confirm.',
        rx_lines: [{ generic: 'Naproxen', brand: 'Naprosyn', strength: '500mg', form: 'tablet', frequency: 'BD PRN', duration_days: 7 }],
        disposition: 'diagnostics' },
      { date: '2026-02-22', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Lab review', 'Joint pain'],
        cc_text: 'MRI: complete ACL tear + medial meniscus posterior horn tear.',
        vitals: { bp_sys: 122, bp_dia: 76, hr: 70, temp_c: 36.7, spo2: 99, weight_kg: 72, height_cm: 178, pain: 3 },
        exam_findings: 'Same.',
        assessment_codes: ['S83.5'],
        assessment_text: 'For ACL reconstruction + meniscus repair. Pre-op workup done.',
        rx_lines: [],
        disposition: 'admit', referral_target: 'Surgical OT booking — ACL recon + meniscectomy' },
      { date: '2026-03-28', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Post-op week 1. Pain manageable, swelling reducing.',
        vitals: { bp_sys: 120, bp_dia: 74, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 71, height_cm: 178, pain: 4 },
        exam_findings: 'Sutures clean. Mild effusion. ROM 0-60.',
        assessment_codes: ['Z47.81'],
        assessment_text: 'Post-op recovery as expected. Physio referral.',
        rx_lines: [
          { generic: 'Etoricoxib', brand: 'Etoshine', strength: '90mg', form: 'tablet', frequency: 'OD', duration_days: 7 },
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'TDS PRN', duration_days: 14 },
        ],
        disposition: 'follow_up', follow_up_days: 14, referral_target: 'Sports physio' },
      { date: '2026-04-25', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Routine post-op. Pain controlled. Physio progressing — ROM 0-110 now.',
        vitals: { bp_sys: 118, bp_dia: 72, hr: 68, temp_c: 36.7, spo2: 99, weight_kg: 71, height_cm: 178, pain: 1 },
        exam_findings: 'No effusion. Wound healed.',
        assessment_codes: ['Z47.81'],
        assessment_text: 'Progressing. Continue physio.',
        rx_lines: [{ generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'PRN', duration: '2 months' }],
        disposition: 'follow_up', follow_up_days: 60 },
    ],
    lab_cycles: [
      { date: '2026-02-18', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [{ raw_text: 'MRI left knee', canonical_key: 'mri_knee', display_name: 'MRI Left Knee' }],
        results: [{ canonical_key: 'mri_knee', display_name: 'MRI Left Knee', value_text: 'Complete ACL tear at midsubstance. Posterior horn medial meniscus complex tear. MCL intact. PCL intact.', unit: '', reference_range: 'normal' }] },
    ],
    override_events: [],
  },
];
