/**
 * v2.0.0 seed — patient stories batch 8 (final 9 new patients).
 * EHRC-2026-044 through 050.
 */
import type { SeedPatient } from './types';

export const PATIENTS_BATCH_8: SeedPatient[] = [
  // 44. Janaki Devi — 65F — Sahakar Nagar — retired
  // Diabetic foot ulcer (right), neuropathy, T2DM, CKD stage 3
  {
    mrn: 'EHRC-2026-044', name: 'Janaki Devi', age_years: 65, sex: 'F',
    phone_e164: '+919900112266', known_allergies: null,
    occupation: 'Retired', area: 'Sahakar Nagar',
    primary_doctor_email: 'rajesh.murthy@even.in',
    active_problems: [
      { label: 'Type 2 diabetes mellitus with peripheral neuropathy', since: '2012-04', status: 'active',
        current_meds: ['Insulin Mixtard 30/70 — 18u AM, 12u PM', 'Metformin 1g BD'] },
      { label: 'Right plantar diabetic foot ulcer (healing)', since: '2026-02', status: 'active' },
      { label: 'CKD stage 3a (eGFR 48)', since: '2023-09', status: 'active' },
    ],
    encounters: [
      { date: '2025-07-04', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Diabetes follow-up'],
        cc_text: 'Quarterly review.',
        vitals: { bp_sys: 138, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 64, height_cm: 154, pain: 0 },
        exam_findings: 'Sensory loss to monofilament both soles. Pulses present.',
        assessment_codes: ['E11.4', 'N18.3'],
        assessment_text: 'Long-standing DM with neuropathy + CKD. HbA1c 7.6.',
        rx_lines: [
          { generic: 'Insulin Mixtard 30/70', brand: 'Mixtard', strength: '100u/mL', form: 'pen', frequency: 'BD', duration: '3 months' },
          { generic: 'Metformin', brand: 'Glycomet', strength: '1g', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-04', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Right plantar ulcer noted by daughter. No pain (neuropathic). 2cm at metatarsal head 1.',
        vitals: { bp_sys: 136, bp_dia: 78, hr: 78, temp_c: 36.9, spo2: 98, weight_kg: 64, height_cm: 154, pain: 0 },
        exam_findings: '2cm shallow ulcer, granulation tissue, no eschar. Mild erythema margin. No purulent discharge.',
        assessment_codes: ['E11.621'],
        assessment_text: 'Diabetic foot ulcer, Wagner grade 1. Offloading + dressing + antibiotic.',
        rx_lines: [
          { generic: 'Amoxicillin + Clavulanate', brand: 'Augmentin', strength: '625mg', form: 'tablet', frequency: 'TDS', duration_days: 10 },
          { generic: 'Insulin Mixtard 30/70', brand: 'Mixtard', strength: '100u/mL', form: 'pen', frequency: 'BD', duration: '3 months' },
          { generic: 'Metformin', brand: 'Glycomet', strength: '1g', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 14, referral_target: 'Wound care nurse + podiatry' },
      { date: '2026-03-04', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Ulcer reducing. Now 1cm, clean granulating.',
        vitals: { bp_sys: 134, bp_dia: 78, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 64, height_cm: 154, pain: 0 },
        exam_findings: '1cm ulcer, healing.',
        assessment_codes: ['E11.621'],
        assessment_text: 'Healing well.',
        rx_lines: [{ generic: 'Insulin Mixtard 30/70', brand: 'Mixtard', strength: '100u/mL', form: 'pen', frequency: 'BD', duration: '3 months' }],
        disposition: 'follow_up', follow_up_days: 28 },
      { date: '2026-05-06', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Almost healed. Pinpoint epithelial gap only.',
        vitals: { bp_sys: 132, bp_dia: 76, hr: 74, temp_c: 36.7, spo2: 98, weight_kg: 64, height_cm: 154, pain: 0 },
        exam_findings: 'Almost healed.',
        assessment_codes: ['E11.621'],
        assessment_text: 'Continue offloading + foot care education.',
        rx_lines: [{ generic: 'Insulin Mixtard 30/70', brand: 'Mixtard', strength: '100u/mL', form: 'pen', frequency: 'BD', duration: '3 months' }],
        disposition: 'follow_up', follow_up_days: 60 },
    ],
    lab_cycles: [
      { date: '2025-07-02', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'HbA1c + Crea + ACR', canonical_key: 'dm_panel', display_name: 'DM Quarterly' }],
        results: [
          { canonical_key: 'hba1c', display_name: 'HbA1c', value_numeric: 7.6, unit: '%', reference_range: '<5.7' },
          { canonical_key: 'creatinine', display_name: 'Creatinine', value_numeric: 1.4, unit: 'mg/dL', reference_range: '0.7-1.3' },
          { canonical_key: 'egfr', display_name: 'eGFR', value_numeric: 48, unit: 'mL/min/1.73m²', reference_range: '>60' },
        ] },
      { date: '2026-02-02', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [
          { raw_text: 'Wound swab culture', canonical_key: 'wound_culture', display_name: 'Wound Culture' },
          { raw_text: 'X-ray right foot', canonical_key: 'xray_foot', display_name: 'X-ray foot' },
        ],
        results: [
          { canonical_key: 'wound_culture', display_name: 'Wound Culture', value_text: 'Mild Staph aureus growth, sensitive to Amox-Clav.', unit: '', reference_range: 'no growth' },
          { canonical_key: 'xray_foot', display_name: 'X-ray foot', value_text: 'No osteomyelitis. Mild forefoot calcification.', unit: '', reference_range: 'normal' },
        ] },
    ],
    override_events: [
      { date: '2026-02-04', doctor_email: 'karthik.reddy@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Diabetic foot ulcer, right plantar', status: 'active', note: 'Wagner grade 1.' } },
    ],
  },

  // 45. Krishnamurthy Bhat — 70M — Padmanabha Nagar — retired engineer
  // Atrial fibrillation new diagnosis, started anticoagulation
  {
    mrn: 'EHRC-2026-045', name: 'Krishnamurthy Bhat', age_years: 70, sex: 'M',
    phone_e164: '+919844112266', known_allergies: null,
    occupation: 'Retired civil engineer', area: 'Padmanabha Nagar',
    primary_doctor_email: 'anika.iyer@even.in',
    active_problems: [
      { label: 'New-onset atrial fibrillation (Apr 2026)', since: '2026-04', status: 'active',
        current_meds: ['Apixaban 5mg BD', 'Bisoprolol 2.5mg OD'] },
      { label: 'Hypertension', since: '2018-11', status: 'controlled', current_meds: ['Telmisartan 40mg OD'] },
    ],
    encounters: [
      { date: '2025-08-25', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly BP check. Routine.',
        vitals: { bp_sys: 134, bp_dia: 80, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 168, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I10'],
        assessment_text: 'HTN stable.',
        rx_lines: [{ generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'follow_up', follow_up_days: 180 },
      { date: '2026-04-12', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['Dizziness', 'Chest pain'],
        cc_text: 'Sudden onset palpitations and dizziness 2 days ago. Persistent irregular pulse. No chest pain.',
        vitals: { bp_sys: 140, bp_dia: 88, hr: 124, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 168, pain: 1 },
        exam_findings: 'Irregularly irregular pulse, rate 124. CHA2DS2-VASc 3.',
        assessment_codes: ['I48.0'],
        assessment_text: 'New AF with rapid ventricular response. Need rate control + anticoagulation.',
        rx_lines: [
          { generic: 'Bisoprolol', brand: 'Concor', strength: '2.5mg', form: 'tablet', frequency: 'OD', duration_days: 30 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 30, instructions: 'Anticoagulation.' },
          { generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2026-04-26', doctor_email: 'anika.iyer@even.in', room_name: 'OPD-3',
        cc_chips: ['BP follow-up'],
        cc_text: 'Rate controlled. HR 78. Echo done.',
        vitals: { bp_sys: 132, bp_dia: 80, hr: 78, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 168, pain: 0 },
        exam_findings: 'Irregular but controlled rate.',
        assessment_codes: ['I48.0'],
        assessment_text: 'Echo: LA 4.6cm (dilated), LVEF 55%. Continue.',
        rx_lines: [
          { generic: 'Bisoprolol', brand: 'Concor', strength: '2.5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Apixaban', brand: 'Eliquis', strength: '5mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2026-04-12', ordering_doctor_email: 'anika.iyer@even.in',
        orders: [
          { raw_text: 'ECG + TFT + Echo', canonical_key: 'af_workup', display_name: 'AF Workup' },
        ],
        results: [
          { canonical_key: 'ecg', display_name: 'ECG', value_text: 'Atrial fibrillation, rate 124. No ischaemic changes.', unit: '', reference_range: 'NSR' },
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 2.1, unit: 'µIU/mL', reference_range: '0.4-4.5' },
        ] },
      { date: '2026-04-22', ordering_doctor_email: 'anika.iyer@even.in',
        orders: [{ raw_text: 'Echo', canonical_key: 'echo', display_name: 'Echocardiogram' }],
        results: [
          { canonical_key: 'echo_lvef', display_name: 'LVEF', value_numeric: 55, unit: '%', reference_range: '>55' },
          { canonical_key: 'echo_la_size', display_name: 'LA Size', value_numeric: 4.6, unit: 'cm', reference_range: '<4.0' },
        ] },
    ],
    override_events: [
      { date: '2026-04-12', doctor_email: 'anika.iyer@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'New-onset atrial fibrillation', status: 'active', note: 'CHA2DS2-VASc 3. Apixaban started.' } },
    ],
  },

  // 46. Manisha Goel — 31F — Indiranagar — yoga instructor
  // Multiple sclerosis (relapsing-remitting), on DMT
  {
    mrn: 'EHRC-2026-046', name: 'Manisha Goel', age_years: 31, sex: 'F',
    phone_e164: '+919844998812', known_allergies: null,
    occupation: 'Yoga instructor', area: 'Indiranagar',
    primary_doctor_email: 'vinay.bhardwaj@even.in',
    active_problems: [
      { label: 'Multiple sclerosis, relapsing-remitting (since 2022)', since: '2022-09', status: 'active',
        current_meds: ['Glatiramer acetate 40mg SC 3x weekly'] },
    ],
    encounters: [
      { date: '2025-08-04', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Quarterly. No new relapses in 14 months. EDSS 2.0.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 70, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 165, pain: 0 },
        exam_findings: 'No focal deficit. Sensory intact. Mild residual right pyramidal signs from 2024 relapse.',
        assessment_codes: ['G35'],
        assessment_text: 'MS-RR stable on glatiramer.',
        rx_lines: [{ generic: 'Glatiramer acetate', brand: 'Glatopa', strength: '40mg', form: 'SC injection', frequency: '3x weekly', duration: '3 months' }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-12-14', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'New right leg numbness 5 days ago. Mild gait imbalance.',
        vitals: { bp_sys: 108, bp_dia: 68, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 165, pain: 1 },
        exam_findings: 'Right leg sensory level T10. Mild ataxia. EDSS now 3.0.',
        assessment_codes: ['G35'],
        assessment_text: 'Relapse — needs IV methylpred course. Admission planned.',
        rx_lines: [{ generic: 'Methylprednisolone IV', brand: 'Solu-Medrol', strength: '1g', form: 'IV infusion', frequency: 'OD', duration: '5 days' }],
        disposition: 'admit', referral_target: 'Day care infusion centre' },
      { date: '2026-01-08', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Post-relapse review. Sensory level resolved. Some residual leg fatigue.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 165, pain: 0 },
        exam_findings: 'EDSS 2.5.',
        assessment_codes: ['G35'],
        assessment_text: 'Relapse recovered. Discuss DMT escalation given 2nd relapse in 18 months.',
        rx_lines: [{ generic: 'Glatiramer acetate', brand: 'Glatopa', strength: '40mg', form: 'SC injection', frequency: '3x weekly', duration: '3 months' }],
        disposition: 'follow_up', follow_up_days: 90,
        handoff_note: 'Consider switch to higher-efficacy DMT (ocrelizumab/natalizumab) — discussed at next visit.' },
      { date: '2026-04-08', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Routine. Discussion: switching to Ocrelizumab. JCV status checked.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 165, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['G35'],
        assessment_text: 'JCV negative — Ocrelizumab safe. Plan initiation in 1 month.',
        rx_lines: [{ generic: 'Glatiramer acetate', brand: 'Glatopa', strength: '40mg', form: 'SC injection', frequency: '3x weekly', duration: '1 month', instructions: 'Bridge until Ocrelizumab.' }],
        disposition: 'follow_up', follow_up_days: 30 },
    ],
    lab_cycles: [
      { date: '2025-08-02', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'MRI brain + spine', canonical_key: 'mri_brain_spine', display_name: 'MRI Brain + Spine' }],
        results: [{ canonical_key: 'mri_brain_spine', display_name: 'MRI Brain + Spine', value_text: 'Multiple T2 lesions, stable count from 2024. No new enhancing lesions.', unit: '', reference_range: 'no new lesions' }] },
      { date: '2025-12-20', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'MRI brain + spine (relapse w/u)', canonical_key: 'mri_brain_spine', display_name: 'MRI Brain + Spine — Relapse' }],
        results: [{ canonical_key: 'mri_brain_spine', display_name: 'MRI Brain + Spine', value_text: 'New enhancing lesion thoracic cord T9-T10. Multiple stable cerebral lesions.', unit: '', reference_range: 'no new lesions' }] },
      { date: '2026-04-05', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'JCV antibody', canonical_key: 'jcv_ab', display_name: 'JCV Antibody' }],
        results: [{ canonical_key: 'jcv_ab', display_name: 'JCV Antibody', value_text: 'Negative', unit: '', reference_range: 'negative' }] },
    ],
    override_events: [],
  },

  // 47. Rakesh Murty — 49M — Whitefield — IT director
  // TB (pulmonary) — recently completed Cat I DOTS
  {
    mrn: 'EHRC-2026-047', name: 'Rakesh Murty', age_years: 49, sex: 'M',
    phone_e164: '+919844887766', known_allergies: 'Pyrazinamide (hepatotoxicity 2025)',
    occupation: 'IT director', area: 'Whitefield',
    primary_doctor_email: 'lakshmi.naidu@even.in',
    active_problems: [
      { label: 'Pulmonary TB — completed treatment (RHE 6 months)', since: '2025-09', status: 'controlled' },
    ],
    encounters: [
      { date: '2025-09-08', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Cough', 'Fever'],
        cc_text: 'Productive cough 6 weeks, evening fever, weight loss 4kg.',
        vitals: { bp_sys: 118, bp_dia: 76, hr: 92, rr: 18, temp_c: 38.2, spo2: 96, weight_kg: 64, height_cm: 172, pain: 1 },
        exam_findings: 'Upper zone crepts right. Cervical LN palpable.',
        assessment_codes: ['A15.0'],
        assessment_text: 'Pulmonary TB suspected.',
        rx_lines: [],
        disposition: 'diagnostics' },
      { date: '2025-09-22', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Cough', 'Lab review'],
        cc_text: 'CBNAAT positive for MTB. Rifampicin sensitive.',
        vitals: { bp_sys: 118, bp_dia: 76, hr: 88, rr: 18, temp_c: 37.8, spo2: 97, weight_kg: 64, height_cm: 172, pain: 0 },
        exam_findings: 'As before.',
        assessment_codes: ['A15.0'],
        assessment_text: 'Confirmed PTB. Start Cat I DOTS.',
        rx_lines: [
          { generic: 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol (4FDC)', brand: '4FDC', strength: 'as per weight', form: 'tablet', frequency: 'OD', duration: '2 months intensive', timing: 'empty stomach' },
        ],
        disposition: 'follow_up', follow_up_days: 30 },
      { date: '2025-10-15', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Lab review'],
        cc_text: 'Routine. LFT shows ALT 380 — drug-induced hepatitis.',
        vitals: { bp_sys: 116, bp_dia: 74, hr: 84, rr: 16, temp_c: 36.7, spo2: 98, weight_kg: 65, height_cm: 172, pain: 0 },
        exam_findings: 'Mild scleral icterus.',
        assessment_codes: ['A15.0'],
        assessment_text: 'DIH. Hold drugs, reintroduce sequentially.',
        rx_lines: [{ generic: 'Streptomycin', brand: 'Strepto', strength: '0.75g', form: 'IM injection', frequency: 'OD', duration: '14 days', instructions: 'Bridge therapy while LFT recovers.' }],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2025-11-05', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Cough'],
        cc_text: 'LFT normalised. Reintroducing INH + Rifampicin + Ethambutol, no Pyrazinamide.',
        vitals: { bp_sys: 116, bp_dia: 74, hr: 80, rr: 16, temp_c: 36.7, spo2: 98, weight_kg: 66, height_cm: 172, pain: 0 },
        exam_findings: 'Clear chest, no LN.',
        assessment_codes: ['A15.0'],
        assessment_text: 'RHE regimen, extending continuation to 9 months total.',
        rx_lines: [
          { generic: 'Rifampicin + Isoniazid + Ethambutol (3FDC)', brand: '3FDC', strength: 'as per weight', form: 'tablet', frequency: 'OD', duration: '7 months', timing: 'empty stomach' },
        ],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2026-02-12', doctor_email: 'lakshmi.naidu@even.in', room_name: 'OPD-7',
        cc_chips: ['Cough'],
        cc_text: 'Quarterly. Asymptomatic. Weight up 6kg.',
        vitals: { bp_sys: 118, bp_dia: 76, hr: 76, rr: 16, temp_c: 36.7, spo2: 98, weight_kg: 70, height_cm: 172, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['A15.0'],
        assessment_text: 'Excellent response.',
        rx_lines: [{ generic: 'Rifampicin + Isoniazid + Ethambutol (3FDC)', brand: '3FDC', strength: 'as per weight', form: 'tablet', frequency: 'OD', duration: '3 months' }],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-09-15', ordering_doctor_email: 'lakshmi.naidu@even.in',
        orders: [
          { raw_text: 'CBNAAT sputum', canonical_key: 'cbnaat', display_name: 'CBNAAT Sputum' },
          { raw_text: 'CXR + LFT + HIV', canonical_key: 'tb_workup', display_name: 'TB Workup' },
        ],
        results: [
          { canonical_key: 'cbnaat', display_name: 'CBNAAT', value_text: 'MTB detected, rifampicin sensitive', unit: '', reference_range: 'not detected' },
          { canonical_key: 'cxr', display_name: 'CXR', value_text: 'Right upper zone fibroinfiltrative shadows, no cavity.', unit: '', reference_range: 'normal' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 32, unit: 'U/L', reference_range: '7-56' },
          { canonical_key: 'hiv_screen', display_name: 'HIV Screen', value_text: 'Negative', unit: '', reference_range: 'negative' },
        ] },
      { date: '2025-10-12', ordering_doctor_email: 'lakshmi.naidu@even.in',
        orders: [{ raw_text: 'LFT', canonical_key: 'lft', display_name: 'LFT' }],
        results: [
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 380, unit: 'U/L', reference_range: '7-56', is_critical: true },
          { canonical_key: 'ast', display_name: 'AST', value_numeric: 242, unit: 'U/L', reference_range: '10-40' },
          { canonical_key: 'total_bilirubin', display_name: 'Bilirubin', value_numeric: 2.4, unit: 'mg/dL', reference_range: '<1.2' },
        ] },
      { date: '2025-11-02', ordering_doctor_email: 'lakshmi.naidu@even.in',
        orders: [{ raw_text: 'LFT recheck', canonical_key: 'lft', display_name: 'LFT' }],
        results: [{ canonical_key: 'alt', display_name: 'ALT', value_numeric: 42, unit: 'U/L', reference_range: '7-56' }] },
    ],
    override_events: [
      { date: '2025-10-15', doctor_email: 'lakshmi.naidu@even.in', target_kind: 'allergy', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Pyrazinamide', note: 'Drug-induced hepatitis Oct 2025, ALT 380. Avoid lifelong.' } },
    ],
  },

  // 48. Yashika Roy — 27F — Bellandur — pediatric resident
  // Active dengue, vasovagal collapse 1 month ago
  {
    mrn: 'EHRC-2026-048', name: 'Yashika Roy', age_years: 27, sex: 'F',
    phone_e164: '+919900445522', known_allergies: null,
    occupation: 'Pediatric resident doctor', area: 'Bellandur',
    primary_doctor_email: 'aditya.sharma@even.in',
    active_problems: [],
    encounters: [
      { date: '2026-04-10', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Fever', 'Body ache'],
        cc_text: 'High fever 39.5C, retro-orbital pain, body ache, headache. Day 3 of illness.',
        vitals: { bp_sys: 110, bp_dia: 68, hr: 104, temp_c: 39.4, spo2: 98, weight_kg: 52, height_cm: 162, pain: 5 },
        exam_findings: 'No rash. No bleeding. Mild conjunctival suffusion.',
        assessment_codes: ['A90'],
        assessment_text: 'Likely dengue. NS1 + platelet + Hct check.',
        rx_lines: [
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'QID', duration_days: 5, instructions: 'Avoid NSAIDs.' },
          { generic: 'ORS', strength: '-', form: 'sachet', frequency: 'PRN', duration: '1 week' },
        ],
        disposition: 'diagnostics' },
      { date: '2026-04-12', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Fever', 'Lab review'],
        cc_text: 'NS1 positive. Platelets 95k (was 142). Hct 42 (was 40).',
        vitals: { bp_sys: 102, bp_dia: 64, hr: 88, temp_c: 38.4, spo2: 98, weight_kg: 51, height_cm: 162, pain: 3 },
        exam_findings: 'Mild conjunctival suffusion. No bleeding tendencies. No third-space accumulation.',
        assessment_codes: ['A90'],
        assessment_text: 'Confirmed dengue, no warning signs. Outpatient with daily review.',
        rx_lines: [
          { generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'QID PRN', duration_days: 5 },
          { generic: 'ORS', strength: '-', form: 'sachet', frequency: 'TDS', duration: '1 week' },
        ],
        disposition: 'follow_up', follow_up_days: 1 },
      { date: '2026-04-14', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Fever'],
        cc_text: 'Critical phase day 5. Platelets 42k, hct 44. Improving — defervescence achieved.',
        vitals: { bp_sys: 108, bp_dia: 70, hr: 80, temp_c: 36.9, spo2: 98, weight_kg: 51, height_cm: 162, pain: 1 },
        exam_findings: 'Improving.',
        assessment_codes: ['A90'],
        assessment_text: 'Recovery phase. Plt nadir achieved.',
        rx_lines: [],
        disposition: 'follow_up', follow_up_days: 3 },
      { date: '2026-04-22', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Fever'],
        cc_text: 'Recovered. Plt 188k. Energy returning.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 52, height_cm: 162, pain: 0 },
        exam_findings: 'Healthy.',
        assessment_codes: ['A90'],
        assessment_text: 'Dengue resolved.',
        rx_lines: [],
        disposition: 'discharge' },
    ],
    lab_cycles: [
      { date: '2026-04-11', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [
          { raw_text: 'NS1 + Dengue IgM/IgG + CBC', canonical_key: 'dengue_panel', display_name: 'Dengue Panel' },
        ],
        results: [
          { canonical_key: 'dengue_ns1', display_name: 'Dengue NS1', value_text: 'Positive', unit: '', reference_range: 'negative' },
          { canonical_key: 'platelets', display_name: 'Platelets', value_numeric: 95, unit: 'x10^3/µL', reference_range: '150-450' },
          { canonical_key: 'hematocrit', display_name: 'Hematocrit', value_numeric: 42, unit: '%', reference_range: '36-46 (F)' },
        ] },
      { date: '2026-04-14', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'CBC', canonical_key: 'cbc', display_name: 'CBC' }],
        results: [
          { canonical_key: 'platelets', display_name: 'Platelets', value_numeric: 42, unit: 'x10^3/µL', reference_range: '150-450', is_critical: true },
          { canonical_key: 'hematocrit', display_name: 'Hematocrit', value_numeric: 44, unit: '%', reference_range: '36-46 (F)' },
        ] },
      { date: '2026-04-20', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'CBC', canonical_key: 'cbc', display_name: 'CBC' }],
        results: [{ canonical_key: 'platelets', display_name: 'Platelets', value_numeric: 188, unit: 'x10^3/µL', reference_range: '150-450' }] },
    ],
    override_events: [],
  },

  // 49. Suma Hegde — 36F — JP Nagar — chartered accountant
  // Migraine + comorbid epilepsy, child-bearing age (planning)
  {
    mrn: 'EHRC-2026-049', name: 'Suma Hegde', age_years: 36, sex: 'F',
    phone_e164: '+919844998822', known_allergies: 'Valproate (intolerable weight gain 2024)',
    occupation: 'Chartered accountant', area: 'JP Nagar',
    primary_doctor_email: 'vinay.bhardwaj@even.in',
    active_problems: [
      { label: 'Focal-onset epilepsy', since: '2020-04', status: 'controlled', current_meds: ['Lamotrigine 200mg BD'] },
      { label: 'Migraine without aura', since: '2018-08', status: 'controlled', current_meds: ['Propranolol 40mg BD'] },
    ],
    encounters: [
      { date: '2025-07-08', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Quarterly. Seizure-free 14 months. Migraine 1/month.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 162, pain: 0 },
        exam_findings: 'Neuro intact.',
        assessment_codes: ['G40.2', 'G43.0'],
        assessment_text: 'Both well-controlled.',
        rx_lines: [
          { generic: 'Lamotrigine', brand: 'Lamictal', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-11-04', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Routine. Planning pregnancy — folate supplementation started.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 70, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 162, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['G40.2'],
        assessment_text: 'Pre-conception counsel. Lamotrigine safe in pregnancy, levels need monitoring.',
        rx_lines: [
          { generic: 'Lamotrigine', brand: 'Lamictal', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 180, instructions: 'For pre-conception.' },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-12', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Routine. Stable.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 70, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 162, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['G40.2'],
        assessment_text: 'Stable.',
        rx_lines: [
          { generic: 'Lamotrigine', brand: 'Lamictal', strength: '200mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Propranolol', brand: 'Inderal', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-05', ordering_doctor_email: 'vinay.bhardwaj@even.in',
        orders: [{ raw_text: 'Lamotrigine level + CBC + LFT', canonical_key: 'aed_monitoring', display_name: 'AED Monitoring' }],
        results: [
          { canonical_key: 'lamotrigine_level', display_name: 'Lamotrigine Level', value_numeric: 8.2, unit: 'µg/mL', reference_range: '4-18' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 28, unit: 'U/L', reference_range: '7-56' },
        ] },
    ],
    override_events: [],
  },

  // 50. Shyam Sundar — 58M — Vidyaranyapura — auto-rickshaw driver
  // Newly diagnosed prostate cancer (low-risk), on active surveillance
  {
    mrn: 'EHRC-2026-050', name: 'Shyam Sundar', age_years: 58, sex: 'M',
    phone_e164: '+919844112277', known_allergies: null,
    occupation: 'Auto-rickshaw driver', area: 'Vidyaranyapura',
    primary_doctor_email: 'chandrika.kambam@even.in',
    active_problems: [
      { label: 'Prostate adenocarcinoma — low-risk, on active surveillance', since: '2025-12', status: 'active' },
      { label: 'Essential hypertension', since: '2020-04', status: 'controlled', current_meds: ['Telmisartan 40mg OD'] },
    ],
    encounters: [
      { date: '2025-09-22', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up', 'Burning urination'],
        cc_text: 'BP routine. Notes increasing urinary frequency + nocturia.',
        vitals: { bp_sys: 134, bp_dia: 82, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 168, pain: 0 },
        exam_findings: 'DRE: prostate enlarged smooth, no nodules.',
        assessment_codes: ['I10', 'N40'],
        assessment_text: 'BPH suspected. PSA ordered.',
        rx_lines: [{ generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'diagnostics' },
      { date: '2025-10-22', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'PSA 6.4 — elevated. Will refer for prostate MRI + biopsy.',
        vitals: { bp_sys: 134, bp_dia: 82, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 168, pain: 0 },
        exam_findings: 'Same.',
        assessment_codes: ['R97.20'],
        assessment_text: 'Elevated PSA workup.',
        rx_lines: [{ generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'refer', referral_target: 'Urology — MRI + biopsy' },
      { date: '2025-12-04', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['Lab review'],
        cc_text: 'Biopsy: adenocarcinoma Gleason 3+3 = 6 in 2/12 cores. Confined to right lobe.',
        vitals: { bp_sys: 130, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 168, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['C61'],
        assessment_text: 'Low-risk PCa. Active surveillance plan.',
        rx_lines: [{ generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'follow_up', follow_up_days: 90,
        handoff_note: 'Active surveillance plan: PSA q3mo, MRI q12mo, rebiopsy at 12-18mo.' },
      { date: '2026-03-04', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up', 'Lab review'],
        cc_text: 'Quarterly. PSA recheck.',
        vitals: { bp_sys: 132, bp_dia: 80, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 68, height_cm: 168, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['C61'],
        assessment_text: 'PSA stable 6.2. Continue surveillance.',
        rx_lines: [{ generic: 'Telmisartan', brand: 'Telma', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-10-12', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [{ raw_text: 'PSA + free PSA', canonical_key: 'psa_full', display_name: 'PSA Full' }],
        results: [
          { canonical_key: 'psa', display_name: 'PSA', value_numeric: 6.4, unit: 'ng/mL', reference_range: '<4.0' },
          { canonical_key: 'free_psa_pct', display_name: 'Free PSA %', value_numeric: 18, unit: '%', reference_range: '>25 (benign)' },
        ] },
      { date: '2025-11-22', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [
          { raw_text: 'Prostate MRI + biopsy', canonical_key: 'prostate_workup', display_name: 'Prostate Workup' },
        ],
        results: [
          { canonical_key: 'prostate_mri', display_name: 'Prostate MRI', value_text: 'PI-RADS 4 lesion right peripheral zone. Otherwise normal.', unit: '', reference_range: 'PI-RADS 1-2 benign' },
          { canonical_key: 'prostate_biopsy', display_name: 'Prostate Biopsy', value_text: 'Adenocarcinoma Gleason 3+3=6 in 2/12 cores, right peripheral zone. Other cores benign.', unit: '', reference_range: 'benign' },
        ] },
      { date: '2026-03-01', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [{ raw_text: 'PSA', canonical_key: 'psa', display_name: 'PSA' }],
        results: [{ canonical_key: 'psa', display_name: 'PSA', value_numeric: 6.2, unit: 'ng/mL', reference_range: '<4.0' }] },
    ],
    override_events: [
      { date: '2025-12-04', doctor_email: 'chandrika.kambam@even.in', target_kind: 'problem', target_key: '__doctor_added__',
        action: 'add', payload: { label: 'Prostate adenocarcinoma — low-risk, on active surveillance', status: 'active', note: 'Gleason 3+3, ISUP 1. PSA q3mo.' } },
    ],
  },
];
