/**
 * v2.0.0 seed — patient stories batch 5 (7 of 50, completes existing patients).
 * Existing patients EHRC-2026-019 through 025.
 */
import type { SeedPatient } from './types';

export const PATIENTS_BATCH_5: SeedPatient[] = [
  // 19. Divya Joshi — 40F — Whitefield — homemaker — Subclinical hypothyroid → overt
  {
    mrn: 'EHRC-2026-019', name: 'Divya Joshi', age_years: 40, sex: 'F',
    phone_e164: '+919876543219', known_allergies: null,
    occupation: 'Homemaker', area: 'Whitefield',
    primary_doctor_email: 'rajesh.murthy@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Primary hypothyroidism', since: '2025-09', status: 'controlled', current_meds: ['Levothyroxine 50mcg OD'] },
      { label: 'Vitamin D deficiency', since: '2025-09', status: 'controlled', current_meds: ['Cholecalciferol 60k weekly'] },
    ],
    encounters: [
      { date: '2025-09-04', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Annual check-up'],
        cc_text: 'Annual check, reports fatigue + cold intolerance + 4kg weight gain over 8 months.',
        vitals: { bp_sys: 122, bp_dia: 78, hr: 64, temp_c: 36.6, spo2: 98, weight_kg: 68, height_cm: 158, pain: 0 },
        exam_findings: 'BMI 27.2. Slow ankle reflex. Dry skin.',
        assessment_codes: ['Z00.0'],
        assessment_text: 'Suspected hypothyroid — labs ordered.',
        rx_lines: [], disposition: 'diagnostics' },
      { date: '2025-09-22', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Thyroid follow-up', 'Lab review'],
        cc_text: 'TSH 8.4, anti-TPO positive.',
        vitals: { bp_sys: 120, bp_dia: 76, hr: 66, temp_c: 36.6, spo2: 98, weight_kg: 68, height_cm: 158, pain: 0 },
        exam_findings: 'No goitre.',
        assessment_codes: ['E03.9'],
        assessment_text: 'Hashimoto thyroiditis — overt hypothyroid. Starting levothyroxine.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 60, timing: 'empty stomach' }],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2025-12-02', doctor_email: 'rajesh.murthy@even.in',
        cc_chips: ['Thyroid follow-up'],
        cc_text: 'Energy better, lost 2kg.',
        vitals: { bp_sys: 118, bp_dia: 74, hr: 72, temp_c: 36.6, spo2: 98, weight_kg: 66, height_cm: 158, pain: 0 },
        exam_findings: 'Improved.',
        assessment_codes: ['E03.9'],
        assessment_text: 'Responding well. TSH 3.1. Continue.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 180, timing: 'empty stomach' }],
        disposition: 'follow_up', follow_up_days: 180 },
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Thyroid follow-up'],
        cc_text: 'Routine. Doing well.',
        vitals: { bp_sys: 116, bp_dia: 74, hr: 72, temp_c: 36.6, spo2: 98, weight_kg: 65, height_cm: 158, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E03.9'],
        assessment_text: 'Hypothyroid well-controlled.',
        rx_lines: [{ generic: 'Levothyroxine', brand: 'Eltroxin', strength: '50mcg', form: 'tablet', frequency: 'OD', duration_days: 180 }],
        disposition: 'follow_up', follow_up_days: 180 },
    ],
    lab_cycles: [
      { date: '2025-09-15', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'TSH + Vit D + CBC', canonical_key: 'fatigue_panel', display_name: 'Fatigue Panel' }],
        results: [
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 8.4, unit: 'µIU/mL', reference_range: '0.4-4.5' },
          { canonical_key: 'free_t4', display_name: 'Free T4', value_numeric: 0.8, unit: 'ng/dL', reference_range: '0.9-1.7' },
          { canonical_key: 'anti_tpo', display_name: 'Anti-TPO', value_numeric: 380, unit: 'IU/mL', reference_range: '<35' },
          { canonical_key: 'vitamin_d', display_name: 'Vitamin D', value_numeric: 14, unit: 'ng/mL', reference_range: '30-100' },
        ] },
      { date: '2025-11-30', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'TSH', canonical_key: 'tsh', display_name: 'TSH' }],
        results: [{ canonical_key: 'tsh', display_name: 'TSH', value_numeric: 3.1, unit: 'µIU/mL', reference_range: '0.4-4.5' }] },
      { date: '2026-05-15', ordering_doctor_email: 'rajesh.murthy@even.in',
        orders: [{ raw_text: 'TSH + Vit D', canonical_key: 'thyroid_panel', display_name: 'Thyroid Panel' }],
        results: [
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 2.4, unit: 'µIU/mL', reference_range: '0.4-4.5' },
          { canonical_key: 'vitamin_d', display_name: 'Vitamin D', value_numeric: 38, unit: 'ng/mL', reference_range: '30-100' },
        ] },
    ],
    override_events: [],
  },

  // 20. Sandeep Patel — 44M — Indiranagar — sales executive
  // Tobacco use, anxiety, recent gastritis
  {
    mrn: 'EHRC-2026-020', name: 'Sandeep Patel', age_years: 44, sex: 'M',
    phone_e164: '+919876543220', known_allergies: null,
    occupation: 'Sales executive', area: 'Indiranagar',
    primary_doctor_email: 'priya.suresh@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Erosive gastritis', since: '2025-10', status: 'controlled', current_meds: ['Pantoprazole 40mg OD'] },
      { label: 'Tobacco use disorder', since: '2010', status: 'active' },
    ],
    encounters: [
      { date: '2025-10-12', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Abdominal pain'],
        cc_text: 'Epigastric burning for 3 weeks, worse on empty stomach.',
        vitals: { bp_sys: 130, bp_dia: 84, hr: 80, temp_c: 36.7, spo2: 98, weight_kg: 74, height_cm: 175, pain: 6 },
        exam_findings: 'Epigastric tenderness mod. No rebound.',
        assessment_codes: ['K29.7'],
        assessment_text: 'Suspected erosive gastritis. Starting PPI, endoscopy referral if not better in 4 weeks.',
        rx_lines: [
          { generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'BD', duration_days: 28 },
          { generic: 'Sucralfate', brand: 'Sucrafil', strength: '1g', form: 'tablet', frequency: 'TDS', duration_days: 14 },
        ],
        disposition: 'follow_up', follow_up_days: 28 },
      { date: '2025-11-08', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Abdominal pain'],
        cc_text: 'Improved on PPI. Endoscopy done. Antral erosions, H.pylori-negative.',
        vitals: { bp_sys: 128, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 74, height_cm: 175, pain: 2 },
        exam_findings: 'Mild epigastric tenderness only.',
        assessment_codes: ['K29.7'],
        assessment_text: 'Erosive gastritis improving. Continue PPI. Counseling re: tobacco.',
        rx_lines: [{ generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 60 }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-02-19', doctor_email: 'priya.suresh@even.in', room_name: 'OPD-5',
        cc_chips: ['Acid reflux'],
        cc_text: 'Routine. Pain controlled.',
        vitals: { bp_sys: 128, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 74, height_cm: 175, pain: 1 },
        exam_findings: 'Stable.',
        assessment_codes: ['K29.7'],
        assessment_text: 'Stable. Step-down PPI.',
        rx_lines: [{ generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 30 }],
        disposition: 'discharge' },
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Headache'],
        cc_text: 'Tension headache 5 days, stress at work peaking.',
        vitals: { bp_sys: 138, bp_dia: 86, hr: 84, temp_c: 36.7, spo2: 98, weight_kg: 74, height_cm: 175, pain: 4 },
        exam_findings: 'Neuro intact.',
        assessment_codes: ['G44.2'],
        assessment_text: 'Tension-type headache. Counseling re: smoking + stress.',
        rx_lines: [{ generic: 'Paracetamol', brand: 'Crocin', strength: '650mg', form: 'tablet', frequency: 'TDS PRN', duration_days: 3 }],
        disposition: 'discharge' },
    ],
    lab_cycles: [
      { date: '2025-11-06', ordering_doctor_email: 'priya.suresh@even.in',
        orders: [
          { raw_text: 'Upper GI endoscopy', canonical_key: 'upper_gi_endoscopy', display_name: 'Upper GI Endoscopy' },
          { raw_text: 'H.pylori rapid urease', canonical_key: 'h_pylori', display_name: 'H.pylori test' },
        ],
        results: [
          { canonical_key: 'upper_gi_endoscopy', display_name: 'Upper GI Endoscopy', value_text: 'Multiple antral erosions. No ulcer. Esophagus normal. Duodenum normal.', unit: '', reference_range: 'normal' },
          { canonical_key: 'h_pylori', display_name: 'H.pylori', value_text: 'Negative', unit: '', reference_range: 'negative' },
        ] },
    ],
    override_events: [],
  },

  // 21. Shobha Kumari — 34F — Kalyan Nagar — bank teller
  // Migraine + PCOS, periods irregular
  {
    mrn: 'EHRC-2026-021', name: 'Shobha Kumari', age_years: 34, sex: 'F',
    phone_e164: '+919876543221', known_allergies: null,
    occupation: 'Bank teller', area: 'Kalyan Nagar',
    primary_doctor_email: 'vinay.bhardwaj@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Migraine with aura', since: '2024-09', status: 'controlled', current_meds: ['Topiramate 50mg OD', 'Sumatriptan PRN'] },
      { label: 'Polycystic ovary syndrome', since: '2025-06', status: 'active', current_meds: ['Metformin 500mg BD'] },
    ],
    encounters: [
      { date: '2025-06-30', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Irregular periods, acne, mild hirsutism.',
        vitals: { bp_sys: 116, bp_dia: 74, hr: 78, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 158, pain: 0 },
        exam_findings: 'BMI 25.6. Mild hirsutism.',
        assessment_codes: ['E28.2'],
        assessment_text: 'Suspected PCOS — workup.',
        rx_lines: [], disposition: 'diagnostics' },
      { date: '2025-07-25', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems', 'Lab review'],
        cc_text: 'PCOS confirmed. Starting metformin (insulin elevated).',
        vitals: { bp_sys: 114, bp_dia: 72, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 64, height_cm: 158, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['E28.2'],
        assessment_text: 'PCOS with insulin resistance.',
        rx_lines: [{ generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2025-09-20', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Migraine flare. Visual aura preceding pain. Frequency 4-5/month.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 63, height_cm: 158, pain: 6 },
        exam_findings: 'Neuro intact.',
        assessment_codes: ['G43.1'],
        assessment_text: 'Migraine with aura — preventive needed. Topiramate started.',
        rx_lines: [
          { generic: 'Topiramate', brand: 'Topamac', strength: '25mg', form: 'tablet', frequency: 'OD', duration_days: 30, instructions: 'Up-titrate to 50mg OD over 2 weeks.' },
          { generic: 'Sumatriptan', brand: 'Imitrex', strength: '50mg', form: 'tablet', frequency: 'PRN', duration: '3 months' },
        ],
        disposition: 'follow_up', follow_up_days: 60 },
      { date: '2026-01-15', doctor_email: 'vinay.bhardwaj@even.in',
        cc_chips: ['Headache'],
        cc_text: 'Migraine down to 1/month on Topiramate 50.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 62, height_cm: 158, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['G43.1'],
        assessment_text: 'Excellent response. Continue.',
        rx_lines: [
          { generic: 'Topiramate', brand: 'Topamac', strength: '50mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Headache'],
        cc_text: 'Routine migraine follow-up. Stable.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 72, temp_c: 36.7, spo2: 99, weight_kg: 62, height_cm: 158, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['G43.1'],
        assessment_text: 'Migraine well-controlled.',
        rx_lines: [
          { generic: 'Topiramate', brand: 'Topamac', strength: '50mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Metformin', brand: 'Glycomet', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-07-20', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'PCOS workup', canonical_key: 'pcos_panel', display_name: 'PCOS Panel' }],
        results: [
          { canonical_key: 'lh', display_name: 'LH', value_numeric: 14, unit: 'mIU/mL', reference_range: '2-12' },
          { canonical_key: 'fsh', display_name: 'FSH', value_numeric: 6, unit: 'mIU/mL', reference_range: '3-8' },
          { canonical_key: 'fasting_insulin', display_name: 'Fasting Insulin', value_numeric: 22, unit: 'µIU/mL', reference_range: '<15' },
        ] },
    ],
    override_events: [],
  },

  // 22. Ravi Shankar — 53M — Jayanagar — accountant
  // Chronic LBP, sciatica, recent vertebral disc disease
  {
    mrn: 'EHRC-2026-022', name: 'Ravi Shankar', age_years: 53, sex: 'M',
    phone_e164: '+919876543222', known_allergies: null,
    occupation: 'Accountant', area: 'Jayanagar',
    primary_doctor_email: 'karthik.reddy@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'L4-L5 disc herniation with right S1 radiculopathy', since: '2025-10', status: 'active', current_meds: ['Pregabalin 75mg BD'] },
    ],
    encounters: [
      { date: '2025-10-04', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Back pain'],
        cc_text: 'Low back pain radiating to right buttock + posterior thigh. 3 weeks.',
        vitals: { bp_sys: 130, bp_dia: 82, hr: 78, temp_c: 36.7, spo2: 98, weight_kg: 80, height_cm: 174, pain: 7 },
        exam_findings: 'SLR positive right 40°. Power 5/5. No saddle anaesthesia.',
        assessment_codes: ['M54.4'],
        assessment_text: 'Sciatica. MRI ordered.',
        rx_lines: [
          { generic: 'Diclofenac', brand: 'Voveran', strength: '50mg', form: 'tablet', frequency: 'BD', duration_days: 7 },
          { generic: 'Pregabalin', brand: 'Lyrica', strength: '75mg', form: 'tablet', frequency: 'HS', duration_days: 14 },
          { generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 7 },
        ],
        disposition: 'diagnostics' },
      { date: '2025-10-25', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Back pain', 'Lab review'],
        cc_text: 'MRI shows L4-L5 disc bulge with right S1 nerve root compression.',
        vitals: { bp_sys: 128, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 80, height_cm: 174, pain: 5 },
        exam_findings: 'SLR positive right 50°. Still no neurological deficit.',
        assessment_codes: ['M51.1'],
        assessment_text: 'L4-L5 herniation with right S1 radiculopathy. Conservative for now.',
        rx_lines: [
          { generic: 'Pregabalin', brand: 'Lyrica', strength: '75mg', form: 'tablet', frequency: 'BD', duration_days: 90 },
          { generic: 'Methylcobalamin', brand: 'Mecobal', strength: '1500mcg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 60, referral_target: 'Physiotherapy + pain clinic' },
      { date: '2026-01-08', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Back pain'],
        cc_text: 'Improving. Pain down from 7 to 3. Working from home, no flexion-extension challenges.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 79, height_cm: 174, pain: 3 },
        exam_findings: 'SLR negative bilaterally.',
        assessment_codes: ['M51.1'],
        assessment_text: 'Radiculopathy resolving. Continue conservative.',
        rx_lines: [{ generic: 'Pregabalin', brand: 'Lyrica', strength: '75mg', form: 'tablet', frequency: 'BD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Back pain'],
        cc_text: 'Stable, mild residual ache. Wants to taper Pregabalin.',
        vitals: { bp_sys: 124, bp_dia: 78, hr: 72, temp_c: 36.7, spo2: 98, weight_kg: 79, height_cm: 174, pain: 2 },
        exam_findings: 'Stable.',
        assessment_codes: ['M51.1'],
        assessment_text: 'Plan taper Pregabalin over 4 weeks.',
        rx_lines: [{ generic: 'Pregabalin', brand: 'Lyrica', strength: '50mg', form: 'tablet', frequency: 'BD', duration_days: 30, instructions: 'Taper from 75mg BD.' }],
        disposition: 'follow_up', follow_up_days: 30 },
    ],
    lab_cycles: [
      { date: '2025-10-18', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [{ raw_text: 'MRI lumbosacral spine', canonical_key: 'mri_lumbar', display_name: 'MRI Lumbosacral Spine' }],
        results: [{ canonical_key: 'mri_lumbar', display_name: 'MRI Lumbosacral', value_text: 'L4-L5 disc bulge with right paracentral protrusion compressing right S1 root. L5-S1 mild bulge. No spinal stenosis.', unit: '', reference_range: 'normal' }] },
    ],
    override_events: [],
  },

  // 23. Pooja Shenoy — 32F — RT Nagar — teacher
  // Allergic rhinitis + eczema, atopic background
  {
    mrn: 'EHRC-2026-023', name: 'Pooja Shenoy', age_years: 32, sex: 'F',
    phone_e164: '+919876543223', known_allergies: 'Dust mites, pollen',
    occupation: 'Primary school teacher', area: 'RT Nagar',
    primary_doctor_email: 'meera.pillai@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Atopic dermatitis', since: '2014', status: 'active', current_meds: ['Tacrolimus ointment 0.03%'] },
      { label: 'Allergic rhinitis', since: '2010', status: 'active', current_meds: ['Fluticasone nasal'] },
    ],
    encounters: [
      { date: '2025-07-22', doctor_email: 'meera.pillai@even.in', room_name: 'OPD-9',
        cc_chips: ['Rash / itching'],
        cc_text: 'Eczema flare in flexures, severe itching. Disturbing sleep.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 55, height_cm: 160, pain: 0 },
        exam_findings: 'Lichenified plaques antecubital fossa + popliteal fossa. Excoriations.',
        assessment_codes: ['L20.9'],
        assessment_text: 'Atopic dermatitis flare. Topical steroid short course + emollient.',
        rx_lines: [
          { generic: 'Mometasone furoate', brand: 'Elocon', strength: '0.1%', form: 'cream', frequency: 'BD', duration_days: 14 },
          { generic: 'Tacrolimus', brand: 'Tacroz', strength: '0.03%', form: 'ointment', frequency: 'BD', duration_days: 60, instructions: 'For maintenance after steroid.' },
          { generic: 'Levocetirizine', brand: 'Levocet', strength: '5mg', form: 'tablet', frequency: 'HS', duration_days: 14 },
        ],
        disposition: 'follow_up', follow_up_days: 21 },
      { date: '2025-12-05', doctor_email: 'meera.pillai@even.in', room_name: 'OPD-9',
        cc_chips: ['Rash / itching'],
        cc_text: 'Eczema stable on tacrolimus. Coming in for routine.',
        vitals: { bp_sys: 112, bp_dia: 72, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 55, height_cm: 160, pain: 0 },
        exam_findings: 'Skin much better.',
        assessment_codes: ['L20.9'],
        assessment_text: 'Stable.',
        rx_lines: [{ generic: 'Tacrolimus', brand: 'Tacroz', strength: '0.03%', form: 'ointment', frequency: 'BD', duration_days: 90 }],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-03-14', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Cold'],
        cc_text: 'Allergic rhinitis flare seasonal. Sneezing, runny nose.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 55, height_cm: 160, pain: 0 },
        exam_findings: 'Boggy nasal mucosa.',
        assessment_codes: ['J30.9'],
        assessment_text: 'Seasonal AR.',
        rx_lines: [
          { generic: 'Fluticasone nasal spray', brand: 'Flonase', strength: '50mcg', form: 'spray', frequency: 'BD', duration_days: 30 },
          { generic: 'Levocetirizine', brand: 'Levocet', strength: '5mg', form: 'tablet', frequency: 'HS', duration_days: 14 },
        ],
        disposition: 'discharge' },
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Rash / itching'],
        cc_text: 'Minor flare neck + hands.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 74, temp_c: 36.7, spo2: 99, weight_kg: 55, height_cm: 160, pain: 0 },
        exam_findings: 'Minor erythema neck.',
        assessment_codes: ['L20.9'],
        assessment_text: 'Mild AD flare.',
        rx_lines: [{ generic: 'Tacrolimus', brand: 'Tacroz', strength: '0.03%', form: 'ointment', frequency: 'BD', duration_days: 28 }],
        disposition: 'follow_up', follow_up_days: 28 },
    ],
    lab_cycles: [],
    override_events: [],
  },

  // 24. Manoj Verma — 47M — Sahakar Nagar — restaurant owner
  // Alcohol-related fatty liver, recent gout flare
  {
    mrn: 'EHRC-2026-024', name: 'Manoj Verma', age_years: 47, sex: 'M',
    phone_e164: '+919876543224', known_allergies: null,
    occupation: 'Restaurant owner', area: 'Sahakar Nagar',
    primary_doctor_email: 'chandrika.kambam@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Alcohol-related liver disease', since: '2024-05', status: 'active' },
      { label: 'Gout', since: '2025-08', status: 'controlled', current_meds: ['Allopurinol 100mg OD'] },
      { label: 'Hypertension', since: '2022-06', status: 'controlled', current_meds: ['Amlodipine 5mg OD'] },
    ],
    encounters: [
      { date: '2025-08-14', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Acute right big toe pain, swelling, redness, 24 hours.',
        vitals: { bp_sys: 138, bp_dia: 84, hr: 82, temp_c: 37.4, spo2: 98, weight_kg: 86, height_cm: 175, pain: 8 },
        exam_findings: 'Right 1st MTP swollen, hot, erythematous, extremely tender.',
        assessment_codes: ['M10.9'],
        assessment_text: 'Acute gouty arthritis 1st MTP. Treat acutely + start ULT after 2 weeks.',
        rx_lines: [
          { generic: 'Colchicine', brand: 'Zycolchin', strength: '0.5mg', form: 'tablet', frequency: 'BD', duration_days: 7 },
          { generic: 'Naproxen', brand: 'Naprosyn', strength: '500mg', form: 'tablet', frequency: 'BD', duration_days: 5 },
          { generic: 'Pantoprazole', brand: 'Pantop', strength: '40mg', form: 'tablet', frequency: 'OD', duration_days: 5 },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
      { date: '2025-09-02', doctor_email: 'karthik.reddy@even.in', room_name: 'OPD-6',
        cc_chips: ['Joint pain'],
        cc_text: 'Acute attack settled. Uric acid 9.2 on labs.',
        vitals: { bp_sys: 134, bp_dia: 82, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 86, height_cm: 175, pain: 1 },
        exam_findings: 'No active arthritis.',
        assessment_codes: ['M10.9'],
        assessment_text: 'Gout — start urate-lowering therapy.',
        rx_lines: [
          { generic: 'Allopurinol', brand: 'Zyloric', strength: '100mg', form: 'tablet', frequency: 'OD', duration_days: 30, instructions: 'Up-titrate to 300mg after 1 month.' },
          { generic: 'Colchicine', brand: 'Zycolchin', strength: '0.5mg', form: 'tablet', frequency: 'OD', duration_days: 90, instructions: 'Prophylaxis during ULT initiation.' },
        ],
        disposition: 'follow_up', follow_up_days: 30 },
      { date: '2025-12-18', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up'],
        cc_text: 'Routine BP. Reports alcohol intake "moderate" — admits 4-5 drinks/day.',
        vitals: { bp_sys: 142, bp_dia: 88, hr: 80, temp_c: 36.7, spo2: 98, weight_kg: 86, height_cm: 175, pain: 0 },
        exam_findings: 'Mild hepatomegaly. No stigmata of CLD.',
        assessment_codes: ['I10', 'K70.9'],
        assessment_text: 'HTN sub-optimal. Alcohol-related liver disease. Counseled.',
        rx_lines: [
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Allopurinol', brand: 'Zyloric', strength: '100mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      { date: '2026-03-08', doctor_email: 'chandrika.kambam@even.in',
        cc_chips: ['BP follow-up', 'Lab review'],
        cc_text: 'LFT improving with reduced alcohol. No further gout flares.',
        vitals: { bp_sys: 134, bp_dia: 82, hr: 78, temp_c: 36.7, spo2: 98, weight_kg: 84, height_cm: 175, pain: 0 },
        exam_findings: 'Liver edge less palpable.',
        assessment_codes: ['I10', 'K70.9'],
        assessment_text: 'Improving. Continue.',
        rx_lines: [
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Allopurinol', brand: 'Zyloric', strength: '100mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
      // Today — patient in waiting lane
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['BP follow-up'],
        cc_text: 'Quarterly review. Doing well.',
        vitals: { bp_sys: 132, bp_dia: 80, hr: 76, temp_c: 36.7, spo2: 98, weight_kg: 83, height_cm: 175, pain: 0 },
        exam_findings: 'Stable.',
        assessment_codes: ['I10', 'K70.9'],
        assessment_text: 'All stable.',
        rx_lines: [
          { generic: 'Amlodipine', brand: 'Amlong', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Allopurinol', brand: 'Zyloric', strength: '100mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
        ],
        disposition: 'follow_up', follow_up_days: 90 },
    ],
    lab_cycles: [
      { date: '2025-08-30', ordering_doctor_email: 'karthik.reddy@even.in',
        orders: [{ raw_text: 'Uric acid + Lipid + LFT', canonical_key: 'gout_panel', display_name: 'Gout Workup' }],
        results: [
          { canonical_key: 'uric_acid', display_name: 'Serum Uric Acid', value_numeric: 9.2, unit: 'mg/dL', reference_range: '3.5-7.2 (M)' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 92, unit: 'U/L', reference_range: '7-56', is_critical: false },
          { canonical_key: 'ast', display_name: 'AST', value_numeric: 124, unit: 'U/L', reference_range: '10-40' },
          { canonical_key: 'ggt', display_name: 'GGT', value_numeric: 168, unit: 'U/L', reference_range: '8-61' },
        ] },
      { date: '2026-03-04', ordering_doctor_email: 'chandrika.kambam@even.in',
        orders: [{ raw_text: 'Uric acid + LFT', canonical_key: 'liver_uric_panel', display_name: 'LFT + Uric Acid' }],
        results: [
          { canonical_key: 'uric_acid', display_name: 'Serum Uric Acid', value_numeric: 6.8, unit: 'mg/dL', reference_range: '3.5-7.2 (M)' },
          { canonical_key: 'alt', display_name: 'ALT', value_numeric: 58, unit: 'U/L', reference_range: '7-56' },
          { canonical_key: 'ggt', display_name: 'GGT', value_numeric: 112, unit: 'U/L', reference_range: '8-61' },
        ] },
    ],
    override_events: [],
  },

  // 25. Asha Pai — 26F — Yelahanka — graphic designer
  // Newly pregnant, first OPD visit for confirmation
  {
    mrn: 'EHRC-2026-025', name: 'Asha Pai', age_years: 26, sex: 'F',
    phone_e164: '+919876543225', known_allergies: null,
    occupation: 'Graphic designer', area: 'Yelahanka',
    primary_doctor_email: 'aditya.sharma@even.in', existing_in_v1: true,
    active_problems: [
      { label: 'Intrauterine pregnancy (~8 weeks)', since: '2026-04', status: 'active' },
    ],
    encounters: [
      { date: '2025-09-12', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Annual check-up'],
        cc_text: 'Pre-conception counseling, planning pregnancy in next year.',
        vitals: { bp_sys: 108, bp_dia: 70, hr: 76, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 162, pain: 0 },
        exam_findings: 'Healthy.',
        assessment_codes: ['Z31.6'],
        assessment_text: 'Pre-conception planning. Started folic acid.',
        rx_lines: [{ generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 180, instructions: 'Continue through pregnancy if conceives.' }],
        disposition: 'follow_up', follow_up_days: 180 },
      { date: '2026-04-22', doctor_email: 'aditya.sharma@even.in',
        cc_chips: ['Period problems'],
        cc_text: 'Missed period 4 weeks. Home pregnancy test positive.',
        vitals: { bp_sys: 110, bp_dia: 70, hr: 84, temp_c: 36.7, spo2: 99, weight_kg: 57, height_cm: 162, pain: 0 },
        exam_findings: 'No abdominal tenderness.',
        assessment_codes: ['Z34.0'],
        assessment_text: 'Pregnancy confirmed. Will refer to OBG for antenatal care.',
        rx_lines: [
          { generic: 'Folic acid', brand: 'Folvite', strength: '5mg', form: 'tablet', frequency: 'OD', duration_days: 90 },
          { generic: 'Iron + Folic acid', brand: 'Fefol', strength: '60mg+0.5mg', form: 'capsule', frequency: 'OD', duration_days: 90, timing: 'after breakfast' },
        ],
        disposition: 'refer', referral_target: 'OBG OPD — antenatal booking' },
      // Today — patient in waiting lane
      { date: '2026-05-18', doctor_email: 'vinay.bhardwaj@even.in', room_name: 'OPD-1',
        cc_chips: ['Vomiting'],
        cc_text: 'Morning sickness past 2 weeks. Vomiting 2-3 times/day. Tolerating fluids.',
        vitals: { bp_sys: 112, bp_dia: 70, hr: 88, temp_c: 36.7, spo2: 99, weight_kg: 56, height_cm: 162, pain: 1 },
        exam_findings: 'Mucous membranes moist.',
        assessment_codes: ['O21.0'],
        assessment_text: 'Mild morning sickness, no dehydration.',
        rx_lines: [
          { generic: 'Doxylamine + Pyridoxine', brand: 'Doxinate', strength: '10mg+10mg', form: 'tablet', frequency: 'HS', duration_days: 14, instructions: 'Safe in pregnancy.' },
          { generic: 'Ondansetron', brand: 'Emeset', strength: '4mg', form: 'tablet', frequency: 'PRN', duration: '14 days', instructions: 'If breakthrough vomiting only. Cat B in pregnancy.' },
        ],
        disposition: 'follow_up', follow_up_days: 14 },
    ],
    lab_cycles: [
      { date: '2026-04-22', ordering_doctor_email: 'aditya.sharma@even.in',
        orders: [{ raw_text: 'βHCG + Antenatal panel', canonical_key: 'antenatal_booking', display_name: 'Antenatal Booking Panel' }],
        results: [
          { canonical_key: 'beta_hcg', display_name: 'Serum β-HCG', value_numeric: 3450, unit: 'mIU/mL', reference_range: 'positive >5 (pregnancy)' },
          { canonical_key: 'hemoglobin', display_name: 'Hemoglobin', value_numeric: 11.8, unit: 'g/dL', reference_range: '12.0-16.0 (F)' },
          { canonical_key: 'blood_group', display_name: 'Blood Group', value_text: 'B Positive', unit: '', reference_range: 'reportable' },
          { canonical_key: 'tsh', display_name: 'TSH', value_numeric: 2.1, unit: 'µIU/mL', reference_range: '0.4-4.5' },
        ] },
    ],
    override_events: [],
  },
];
